### ISSUE TITLE
Mixing Ember Validations with server side validations

### ISSUE THREAD

**Issue by iwarshak** [DockYard/ember-validations#122]
Is this library designed to be mixed with ember-data's mechanism for server side validations? 
````
model.get('errors.name.firstObject.message')
````

From what I can tell, it seems like errors are not saved in the same way, so that I cannot share error handling code.

**Comment by oswaldoacauan** [comment]
Any news on this matter? There's at least 3 issues open about this topic.

**Comment by TAishwarya** [comment]
Hi . Any solution for this issue?

**Comment by OpakAlex** [comment]
Any updates guys? OR God say do validation only in JS side? 21 century, i understand...

**Comment by martndemus** [comment]
See: https://github.com/DockYard/ember-validations#warning
