### ISSUE TITLE
Validation message for greaterThanOrEqualTo on computed property

### ISSUE THREAD

**Issue by saurori** [DockYard/ember-validations#142]
When I use the greaterThanOrEqualTo validator on a computed property, the validation message comes out as: "must be greater than or equal to computedPropertyName". I tried setting the messages: { greaterThanOrEqualTo: 'custom message' }, but it will not pick up the custom message. You can see it in action here (enter 1 in the text field):

http://emberjs.jsbin.com/uCAbiJEM/3/edit

**Comment by martndemus** [comment]
I am going to close this issue for now, feel free to reopen this issue if you feel like it's still relevant and we should take a look at it.
