### ISSUE TITLE
Single validation rule for two different views?

### ISSUE THREAD

**Issue by danielqiu** [DockYard/ember-validations#147]
I have the validation for an enterprise model, like:

	validations: {
	   name: {
			presence: true,
		},
	    email: {
	        presence: { message: 'required' },        
	        format: { 'with': /^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,4}$/}
	    },
	    smtpHost: {
	    	presence: true,
	    },
	    smtpPort: {
	    	numericality: true
	    },
	    smtpUsername: {
	    	presence: true,
	    },
	    smtpPassword: {
	    	presence: true,
	    },
	    smtpConnectionTimeout: {
	    	numericality: true
	    },	    
	},

In one page, I present all the fields, with the above validation, it works perfectly.

In another page, I present two fields, name and email, with the above validation, it doesn't work, as the other fields aren't presented there but the validation rule requires them.

I see that I have one model and one single validation for two different views which share the same model. Is there a way to make this work?

**Comment by martndemus** [comment]
I am going to close this issue for now, feel free to reopen this issue if you feel like it's still relevant and we should take a look at it.
