### ISSUE TITLE
Validate input as="select"

### ISSUE THREAD

**Issue by Globegitter** [DockYard/ember-validations#151]
I am using ember-easyform in conjunction with this plugin and it is working great so far. Though I just don't seem to be able to get it to validate a select-input. I am giving it a `presence: true` validator but even when I select something I am still getting the error 'can't be blank`.
Is there any way to get this to work with selects?

**Comment by martndemus** [comment]
I am going to close this issue for now, feel free to reopen this issue if you feel like it's still relevant and we should take a look at it.
