### ISSUE TITLE
Change keys injected by EmberValidations.Mixin

### ISSUE THREAD

**Issue by kenips** [DockYard/ember-validations#204]
Currently `EmberValidations.Mixin` injects its errors into the errors key, which coincidentally is used by Ember Data to handle server side errors (see http://emberjs.com/api/data/classes/DS.Errors.html). They currently each have their own convention and are not compatible with each other. Is there any consideration in

a) Making them compatible (which isn't what I'm really asking for)
b) change EmberValidations's errors key name to something else or make it customizable

? Thanks.

**Comment by mar3les** [comment]
I'd really appreciate this as well, making the key configurable (possible via the ENV variable?) would be a great help.

**Comment by martndemus** [comment]
I am going to close this issue for now, feel free to reopen this issue if you feel like it's still relevant and we should take a look at it.
