### ISSUE TITLE
no default message with conditional confirmation validator

### ISSUE THREAD

**Issue by davekaro** [DockYard/ember-validations#210]
When you pass a conditional to the confirmation validation, the `message` is not set.

    password: {
      confirmation: { 'if': 'canValidate' }
    }

The `errors.passwordConfirmation` will be `undefined`. The code only sets `message` if you pass `true` (https://github.com/dockyard/ember-validations/blob/f5586396e92d79b9d7818a116045f81301c0d53b/addon/validators/local/confirmation.js#L17) - 

    password: {
      confirmation: true
    }

Any reason to not follow the same logic as the other validators and set the `message` attribute when it's not passed in (see https://github.com/dockyard/ember-validations/blob/f5586396e92d79b9d7818a116045f81301c0d53b/addon/validators/local/presence.js#L15-L17)?

**Comment by martndemus** [comment]
I am going to close this issue for now, feel free to reopen this issue if you feel like it's still relevant and we should take a look at it.
