### ISSUE TITLE
Streamify All The Things!!

### ISSUE THREAD

**Issue by bcardarella** [DockYard/ember-validations#215]
![](http://i.imgur.com/fhWt95m.jpg)

There have been multiple requests to have validators re-run after option data has been changed. Or if another validator has run. Or when another dependent property has changed. With Ember 1.9's Streams API this can finally be done cleanly.

I will likely dig into it soon and re-write the BaseValidator to have a ValidatorStream that can be notified, when done the validator will re-run. Any number of triggers can cause the validator to re-run.

**Comment by martndemus** [comment]
I am going to close this issue for now, feel free to reopen this issue if you feel like it's still relevant and we should take a look at it.
