### ISSUE TITLE
Promise rejections in Ember 1.9.1

### ISSUE THREAD

**Issue by deepan83** [dockyard/ember-validations#218]
I have just upgraded to Ember 1.9.1 and noticed that certain promises related to ember validations(2.0.0-alpha-1) seem to be now rejected which are causing application issues.

It triggers both an "undefined" and an "Uncaught Error: Assertion Failed: <(unknown mixin):ember578>" error. 

Stack trace below for the "unknown mixin" error,

Uncaught Error: Assertion Failed: <(unknown mixin):ember578> ember.js:3902 
Ember.assert ember.js:29489 
RSVP.onerrorDefault ember.js:48661
 __exports__.default.trigger ember.js:49673 
Promise._onerror ember.js:47904 
publishRejection ember.js:29462
(anonymous function) ember.js:848 
Queue.invoke ember.js:913 
Queue.flush ember.js:718 
DeferredActionQueues.flush ember.js:143 
Backburner.end ember.js:198 
Backburner.run ember.js:217
 Backburner.join ember.js:17946 
run.join ember.js:39254
 __exports__.default.EmberObject.extend._bubbleEvent ember.js:39205 (anonymous function) jquery.js:4665 
jQuery.event.dispatch jquery.js:4333
 jQuery.event.add.elemData.handle

Are there any known issues between Ember 1.9.1 and Ember Validations?

**Comment by bcardarella** [comment]
@deepan83 can you try the master branch? The test suite is running OK against  1.9

**Comment by deepan83** [comment]
Sure @bcardarella 
Seems to be an issue only with conditional validators. Below is my validations object and things work when the conditional vals are commented out.

        validations: {
           postcode:{ presence:{message:'Please enter your full postcode'},format: {"with": /^((([A-PR-UWYZ][0-9])|([A-PR-UWYZ][0-9][0-9])|([A-PR-UWYZ][A-HK-Y][0-9])|([A-PR-UWYZ][A-HK-Y][0-9][0-9])|([A-PR-UWYZ][0-9][A-HJKSTUW])|([A-PR-UWYZ][A-HK-Y][0-9][ABEHMNPRVWXY]))\s?([0-9][ABD-HJLNP-UW-Z]{2})|(GIR)\s?(0AA))$/i,allowBlank: true,message: "Please enter a valid UK postcode"}},
            telephoneNumber:{presence:{message:'Please give us your telephone number','if':"telephoneNumberValidationEnabled"},telnumber:{message:"Your number doesn't look right, please only use numbers, starting with 0",'if':"telephoneNumberValidationEnabled"}},
            gasConsumption: {
                numericality: {
                   // if :"requestGasConsumption",
                    lessThanOrEqualTo:130000,
                    onlyInteger:true,
                    messages:{
                        lessThanOrEqualTo:"hello"
                    }
                }
            },
            elecConsumption: {
                numericality: {
                   // if :"requestElecConsumption",
                    lessThanOrEqualTo:25000,
                    onlyInteger:true
                }
            }
        }

**Comment by deepan83** [comment]
@bcardarella Did some deeper analysis and found a separate stray observer for the conditional validation dependencies(requestGasConsumption and requestElecConsumption) in the application code that was triggering validate again explicitly causing the promise failures. Haven't quite assessed the exact reason behind the promise rejection but at this stage it looks like an app issue. Closing this.

**Comment by bcardarella** [comment]
@deepan83 thank you for following up :)

**Comment by misteroneill** [comment]
I'd like to note here that I'm seeing the same behavior on Ember 1.9.1 and Validations 2.0.0-alpha.2 when calling `validate` manually with a specific property. I've been digging for about an hour and narrowed it down to this validation (on an `Ember.Controller`):

```
    'model.email': {
      length: {
        minimum: 1,
        maximum: 255,
        messages: {
          tooShort: EMAIL_REQUIRED,
          tooLong: EMAIL_REQUIRED
        }
      },
      format: {
        with: Validate.patterns.email,
        message: 'Please enter a valid email address.'
      }
    },
```
There are 3 other validations on this controller that do not trigger the error.

My procedure has been:

- Open the create object form route (creating a new, invalid record).
- Find the controller with the Ember Inspector.
- Assign the controller to `$E`.
- `$E.validate()`

If the `model.email` validation is included, I get the error `Uncaught Error: Assertion Failed: <(unknown mixin):ember1449>` as described in the original issue - but only when calling `validate` manually (never seems to happen when validations are triggered by UI events).

I thought it might be the `.` in there, but I can change `model.email` to just `email` (using an `alias` on the controller) and the problem persists. I can comment out any/all of the validations for it (e.g., `'model.email': {}`) and the problem persists. But if I comment out the entire `model.email` validation (leaving others), the problem disappears.

If I set the value of the `model.email` property to a valid value, the error goes away. If I change it back to an invalid value, the error returns.

This seems weird to me - like it might be a hint of a deeper, perhaps edge-casey, issue. I might spend some free time (what's that?) grokking the ember-validations source to see if I can find some way to confirm it.

**Comment by deepan83** [comment]
@misteroneill You need to handle the array of promises that validate returns(including rejected promises when a validator fails). So just do
this.validate()
      .then(function () {
        return;
      })
      .catch(function (err) {
        return;
      })
      .finally(function () {
        return;
      });

**Comment by misteroneill** [comment]
You're right! Thanks!
