### ISSUE TITLE
Testing error for custom validator with dash in filename

### ISSUE THREAD

**Issue by mattmcginnis** [DockYard/ember-validations#221]
I have a custom validator app/validators/local/password-matches.js

In the controller, it is referenced as passwordMatches

In the controller unit test, it is "needed" like:
```javascript
  needs:[
    'validator:local/password-matches',
  ]
```

This causes an error when the test runs because the validator is not found in the lookupValidator function in ember-validations/addon/mixins.js

```javascript
  var local = container.lookupFactory('validator:local/'+validatorName);
```

The temporary solution to this problem is to rename my validator to app/validators/local/passwordmatches.js and reference it in the controller as passwordmatches and need it in the test like validator:local/passwordmatches.

Ideally, the former style can be supported.

**Comment by bcardarella** [comment]
I suspect this is an issue with the resolver and not ember validations. We just rely upon the resolver to lookup: https://github.com/dockyard/ember-validations/blob/master/addon/mixin.js#L40-L41

@rwjblue @stefanpenner thoughts?

**Comment by mattmcginnis** [comment]
FYI, I have
```json
"ember-resolver": "~0.1.10",
```
in bower.json

**Comment by bcardarella** [comment]
I just confirmed with the master branch of ember-resolver that hyphens are OK. I'll look into ember-validations...

**Comment by bcardarella** [comment]
I'm having a hard time recreating this. Can you try the following in your dev console:

```bash
App.__container__.lookupFactory('validator:local/password-matches')
```

You'll need to substitute "App" for whatever the global variable your app is using.

**Comment by mattmcginnis** [comment]
```
Appname.__container__.lookupFactory('validator:local/password-matches')
```
returns
```
Appname@validator:local/password-matches:
```

## More info
Validator path:
./app/validators/local/password-matches.js

The controller test module's needs: looks like this
```javascript
  needs: [
    'controller:login',
    'ember-validations@validator:local/presence',
    'ember-validations@validator:local/format',
    'ember-validations@validator:local/length',
    'validator:local/password-matches',
  ]


```

Here are the errors I get:
```
Died on test #1     at test (http://localhost:7357/assets/test-support.js:284:13)
    at eval (coveroo/tests/unit/controllers/customer/edit-test.js:19:5)
    at requireModule (http://localhost:7357/assets/vendor.js:77:29)
    at http://localhost:7357/assets/test-loader.js:14:29: Cannot read property 'forEach' of undefined
Source: 	
TypeError: Cannot read property 'forEach' of undefined
    at Object.forEach (http://localhost:7357/assets/vendor.js:27244:17)
    at __exports__.default.Ember.Mixin.create.buildRuleValidator (ember-validations/mixin.js:126:35)
    at __exports__.default.Ember.Mixin.create.buildValidators (ember-validations/mixin.js:92:18)
    at __exports__.default.Ember.Mixin.create.init (ember-validations/mixin.js:74:14)
    at apply (http://localhost:7357/assets/vendor.js:32883:32)
    at superWrapper [as init] (http://localhost:7357/assets/vendor.js:32457:15)
    at apply (http://localhost:7357/assets/vendor.js:32883:32)
    at new Class (http://localhost:7357/assets/vendor.js:47483:9)
    at Function.Mixin.create.create (http://localhost:7357/assets/vendor.js:47941:16)
    at Object.defaultSubject [as subject] (http://localhost:7357/assets/test-support.js:200:22)
```

**Comment by bcardarella** [comment]
Can you check to see what line of code is at: `vendor.js:27244` ? It should correlate to a line of code in `ember-validations/addon/mixin.js` but I can't tell from your stack trace exactly which line.

I was able to confirm that the resolver is working appropriately for the `needs` in a new project. But clearly there is something else going on in your case.

**Comment by mattmcginnis** [comment]
I mainly said that because I rarely, if ever, use dasherized properties in Ember.  I can add a comment in the docs in PR if you want to leave it as is.

**Comment by bcardarella** [comment]
@mattmcginnis nah, if I get the normalization in that should solve all the issues. I'm looking into this tonight

**Comment by rwjblue** [comment]
container.normalize should do most of the work for us I believe.

**Comment by martndemus** [comment]
I am going to close this issue for now, feel free to reopen this issue if you feel like it's still relevant and we should take a look at it.
