### ISSUE TITLE
Inline Validator 'undefined function'

### ISSUE THREAD

**Issue by joshpfosi** [dockyard/ember-validations#222]
When trying to inline a custom validator according to the docs:

    startTime: Em.Validations.validator(function() {
      if (!this.get('newLesson.startTime').match(/\d\d\d\d-\d\d-\d\d \d\d:\d\d/))
        return "can't be blank";
      if (this.get('newLesson.inPast'))
        return 'date has occured';
    })

This returns `undefined is not a function`. Specifically, `Em.Validations` or `Em.Validations.Mixin` or `EmberValidations.Mixin` all do not have a `validator` option that I can tell. Am I using it wrong? I am using the `ember-validations-rails` wrapper gem for your library but I have received no response there so I'm hoping you guys might have an idea.

**Comment by beatle** [comment]
The same issue

**Comment by seawatts** [comment]
Also getting this same error.

**Comment by joshpfosi** [comment]
I never resolved this but switching to ember-cli does solve it and probably should be done anyway if your working with ember in production!

**Comment by seawatts** [comment]
I agree. However, that is not an option at the moment.

On Wed, Jan 21, 2015 at 6:02 AM, Joshua Pfosi <notifications@github.com>
wrote:

> I never resolved this but switching to ember-cli does solve it and
> probably should be done anyway if your working with ember in production!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dockyard/ember-validations/issues/222#issuecomment-70841528>
> .
>



-- 
*Chris Watts* | Software Engineer | cwatts@simplymeasured.com

**Comment by bcardarella** [comment]
Inline validators are only supported on 2.x, which is ember-cli only. It appears you are on Ember 1.x so this API does not exist. master branch's README does not reflect 1.x's
