### ISSUE TITLE
can't make it use ember-cli-i18n. only global Ember.I18n

### ISSUE THREAD

**Issue by oriSomething** [DockYard/ember-validations#224]
hi, is there any plan to support `ember-cli-i18n`, or that i'll need to use a global object of ember-i18n instead of ember cli addon?

maybe, i'm doing something wrong?

thanks

**Comment by bcardarella** [comment]
Yes, I am going to spend February on open source work. I plan to add support then.

**Comment by oriSomething** [comment]
thank!

**Comment by tehmaestro** [comment]
As a workaround, I'm using this, in the route's `setupController` function:

`controller.set('validations.username.presence.message', this.t("errors.blank"));
 controller.set('errors', {});`

And in the `controller`:

`validations: {
            username: {
                presence: { message: "" }
            }
        },`

Also, in `locales/en.js` I have:

`export default {
    title: "Hello",
    errors: {
        blank: "Field cannot be empty",
    }
};`

**Comment by LevelbossMike** [comment]
Are there any updates on this issue? I'd be happy to contribute if I can be of any help here.

**Comment by Baukereg** [comment]
@tehmaestro Thank you for your suggestion, it works perfectly. If you have the validation set directly on a model, you can do it this way:

```
// app/models/whatever.js
setValidation: function() {
  this.set('validations.username.presence.message', this.t("errors.blank"));
}.on('init')
```

**Comment by metz0r** [comment]
Anyone looking at this?

**Comment by bcardarella** [comment]
@metz0r I believe I am blocked on this, hoping to have this resolved soon(ish)

**Comment by danshapir** [comment]
A simple solution that works perfectly :) Even keeps the {{count}} and so on feature.

import Ember from 'ember';
import ValidationMessages from 'ember-validations/messages';

export function initialize(container, application) {
  // application.inject('route', 'foo', 'service:foo');
  var t = container.lookup('utils:t');
  Ember.I18n = {};
  Ember.I18n.t = t;

  ValidationMessages.render = function(attribute, context) {
      if (Ember.I18n) {
        return  this.replaceRegex(Ember.I18n.t('errors.' + attribute, context), context);
      } else {
        return this.replaceRegex(this.defaults[attribute], context)
      }
    };
  ValidationMessages.replaceRegex = function(text, context) {
    var regex = new RegExp("{{(.*?)}}"),
      attributeName = "";

    var result = text;
    while (regex.test(result)) {
      attributeName = regex.exec(result)[1];
      result = result.replace(regex, context[attributeName]);
    }

    return result;
  };

}

export default {
  name: 'validation-i18n',
  after: 't',
  initialize: initialize
};

**Comment by ashrafhasson** [comment]
thanks @danshapir, however, not sure why the need for overriding the `Message.render` method?
Following your example, I've done away with the following minimal initializer:

```javascript
import Ember from 'ember';

export function initialize(container) {
  var t = container.lookup('utils:t');
  Ember.I18n = {};
  Ember.I18n.t = t;
}

export default {
  name: 'validation-i18n',
  after: 't',
  initialize: initialize
};
```

**Comment by danshapir** [comment]
The reason is that the validations are not ordered, meaning you will get a list of objects with a string replacer. The cli i18n expects an ordered array of the words, unlike the hashset used in the regular i18n.

**Comment by wwwdata** [comment]
thanks @ashrafhasson your solution worked for me too. However, is anybody working that this works out of the box? If not it would be very useful to at least mention it in the Readme. There may be more people having the same problem.

**Comment by wwwdata** [comment]
@ashrafhasson i also had to use the render override from @danshapir. Otherwise, placeholders like {{count}} were not replaced correctly. But thanks, it works for now.

**Comment by ashrafhasson** [comment]
@wwwdata I think that is actually correct, my {{count}} arguments are not translated/reflected, it turns out! :)

**Comment by alejandrogutierrez** [comment]
@danshapir I did a little update to your example:

```javascript
import Ember from 'ember';
import ValidationMessages from 'ember-validations/messages';

export function initialize(instance) {
  Ember.I18n = instance.container.lookup('service:i18n');

  ValidationMessages.render = function(attribute, context) {
    return this.replaceRegex(Ember.I18n.t('errors.' + attribute, context), context);
  };

  ValidationMessages.replaceRegex = function(text, context) {
    var regex = new RegExp('{{(.*?)}}'),
        attributeName = '',
        result = text;

    while (regex.test(result)) {
      attributeName = regex.exec(result)[1];
      result = result.replace(regex, context[attributeName]);
    }

    return result;
  };
}

export default {
  name: 'validation-i18n',
  initialize: initialize
};
```

I added in an instance initializer `app/instance-initializers/validation-i18n.js` in order to avoid [deprecation](http://emberjs.com/deprecations/v1.x/#toc_deprecate-access-to-instances-in-initializers).

I'll try to work in a PR to support ember-cli-i18n automatically.

**Comment by gertjanwytynck** [comment]
@alejandrogutierrez This doesn't seems to work anymore.. 

Got the error: 'Uncaught TypeError: instance.container.lookup is not a function'

**Comment by alejandrogutierrez** [comment]
@gertjanwytynck Did you put the code in an "instance" initializer?

**Comment by gertjanwytynck** [comment]
@alejandrogutierrez Ah, stupid me.

Thanks, super fast reply!

**Comment by alejandrogutierrez** [comment]
@gertjanwytynck Great! (y) No problem.

**Comment by martndemus** [comment]
I am going to close this issue for now, feel free to reopen this issue if you feel like it's still relevant and we should take a look at it.
