### ISSUE TITLE
Numericality validation not compatible with Ember data 'number' type

### ISSUE THREAD

**Issue by soulcutter** [DockYard/ember-validations#225]
[Ember Data uses `Number(value)` to serialize attributes](https://github.com/emberjs/data/blob/v1.0.0-beta.14.1/packages/ember-data/lib/transforms/number.js#L49) whereas [Ember Validations matches against a pattern which cleverly allows commas](https://github.com/dockyard/ember-validations/blob/master/addon/patterns.js#L4).

```javascript
var value = '123,456'; // valid via the numericality matcher

// Ember Data will serialize it like so…
Number('123,456') // NaN
```

The resulting behavior is that a field will appear as valid, however upon saving that value is converted to `null`.

I appreciate that those fancy commas are sometimes desirable, however I'm not sure they are a sensible default behavior. Perhaps they could be enabled via a boolean toggle option?

**Comment by martndemus** [comment]
I am going to close this issue for now, feel free to reopen this issue if you feel like it's still relevant and we should take a look at it.
