### ISSUE TITLE
custom validations with 2 word names must be referred to in controller using dash-case

### ISSUE THREAD

**Issue by drewnichols** [DockYard/ember-validations#230]
minor issue but, a validator such as ```my-app/app/validators/local/my-validator``` must be described in the controllers validation hash as ```"my-validator" : { ... }``` and in the test needs array as ```['validator:local/my-validator']```. 

I may be mistaken but I believe the convention is to use camel case in the controllers hash, such as ```myValidator: { ... }```.

as I said.. minor issue

**Comment by bcardarella** [comment]
The convention is to actually move more towards hyphenation in Ember. Files are preferred to be hyphenated, you can camelCase but internally the names are converted to hyphenation.

That being said, camelCase should be supported through that same normalization process, if it is not then that is a bug.

**Comment by mattmcginnis** [comment]
See: https://github.com/dockyard/ember-validations/issues/221

I'd be happy to submit a PR to add something to the docs explaining the need to dasherize.

**Comment by bcardarella** [comment]
@mattmcginnis I think it might be best if I can get a failing test case to work from. I still believe that the hyphenation/camelcasing should "just work" due to the resolver but clearly something else is wrong.

**Comment by drewnichols** [comment]
I may be working from home tomorrow due to a little snowfall here in NYC. I can probably create one. 


Drew Nichols

VP of Engineering

LiftForward, Inc.

261 Madison Avenue, 9th Floor

New York, NY 10016

(646) 228-1322 (cell)

**Comment by martndemus** [comment]
I am going to close this issue for now, feel free to reopen this issue if you feel like it's still relevant and we should take a look at it.
