### ISSUE TITLE
Impossible to build

### ISSUE THREAD

**Issue by karellm** [dockyard/ember-validations#232]
With the latest version of things, the build doesn't work. You get an error `AST contains no nodes at all?`. It is because of the `recast` package that freaks out when a file only contains comments.

I didn't do a PR for this, since I don't know if you prefer to add a line of javascript at the top (`var a;` will do) or simply remove the file. The file concerned is: `/tests/unit/validators/reote/uniqueness_test.js`.

**Comment by bcardarella** [comment]
Can you just wrap the entire file with:

```javascript
if (false) {
  ...
}
```

**Comment by karellm** [comment]
Actually caused the test on #231 to fail. Added it to the PR.
