### ISSUE TITLE
Validate error when we upgraded to ember 1.9.1

### ISSUE THREAD

**Issue by abrahamspaa** [dockyard/ember-validations#233]
I'm getting error when we use .validate(), only in ember 1.9.1 and handle bar 2.0.0.

Please find the below demo,
http://jsbin.com/dunohe/4/edit?html,js,console,output

when we comment out this.validation, then validation is working fine.  
It was working fine in ember 1.8.1 and handlebar 1.3.0. But not in the current version. :(

Is there any alternative solution? 

Thanks

**Comment by joseguti84** [comment]
Hi Abraham, I had the same issue as you but I found the solution in the documentation.

Now, the .validation() function is a promise and you will need change you code. 

https://github.com/dockyard/ember-validations#running-validations

I hope you can solve your problem with this.

Bye

**Comment by abrahamspaa** [comment]
@joseguti84  
Thanks, 
I have changed the code it working fine now.

this.validate().then(function(){
.....
}).catch(function(){
return;
});
