### ISSUE TITLE
Controller tests failing due to cache on v2.0.0-alpha.2

### ISSUE THREAD

**Issue by coleww** [dockyard/ember-validations#234]
On a project at work, we started getting a lot of failing controller tests due to this error: 'Assertion Failed: Cannot call get with 'cache' on an undefined object.'

I  noticed that all of the failing tests depended on ember-validations, and saw that v2.0.0-alpha.2 was released yesterday. It seems like the error must be happening around here:

https://github.com/dockyard/ember-validations/compare/v2.0.0-alpha.1...master#diff-68a377996e559f04a75ca6ba1af084b1R34

I don't know enough about Ember/Qunit internals to see what the issue is, but I wanted to raise this in case others have the same problem. Validations were working in the app, the only issue was in testing. Moreover, some of our integration tests touch on validation functionality, and those were also passing. 

This is what one of the failing tests looked like, just the standard `ember g controller` test:

```
`import { test, moduleFor } from 'ember-qunit'`

moduleFor 'controller:user', 'UserController', {
  needs: ['ember-validations@validator:local/presence',
          'ember-validations@validator:local/format',
          'ember-validations@validator:local/length']
}

test 'it exists', ->
  controller = @subject()
  ok controller
```

Using: 
Ember : 1.7.0
Ember-cli : 0.1.2

Let me know if I can provide any more info

**Comment by bcardarella** [comment]
@coleww is this not happening in alpha.1?

**Comment by ehntoo** [comment]
@bcardarella Also seeing this after pulling in alpha.2.  Reverted to alpha.1 and could no longer reproduce the issue.

**Comment by coleww** [comment]
@bcardarella tests are all passing on alpha.1

**Comment by bcardarella** [comment]
Any chance you guys could create a sample app recreating? I'm not seeing it on my end.

**Comment by ehntoo** [comment]
@bcardarella - Created a minimal demo repo here - https://github.com/ehntoo/ember-validations-234.
See the WutController and corresponding unit test.

**Comment by bcardarella** [comment]
Can you try master branch?

**Comment by ehntoo** [comment]
@bcardarella Still appears to be failing for me in a slightly different manner in the ember-validations-234 project I created as a minimal testcase.
```
not ok 8 PhantomJS 1.9 - WutController: it exists
    ---
        actual: >
            null
        message: >
            Died on test #1     at http://localhost:7357/assets/test-support.js:418
                at test (http://localhost:7357/assets/test-support.js:284)
                at http://localhost:7357/assets/ember-validations-234.js:242
                at http://localhost:7357/assets/vendor.js:77
                at http://localhost:7357/assets/test-loader.js:14: 'undefined' is not an object (evaluating 'cache[validatorName]')
        Log: >
    ...
```

If I apply a similar strategy to line 34 and default the cache to an empty object as well, everything works fine, but my interpretation is that this is defeating the cache entirely as it will be re-created on every validator lookup.  This is fine for my usecase, but I'm unsure about it's general suitability.

**Comment by bcardarella** [comment]
@ehntoo ok, I should have it squashed now. Check out master. I've also added a regression test for this bug

**Comment by ehntoo** [comment]
@bcardarella Looks good to me. Thanks for the quick response on this!

**Comment by samselikoff** [comment]
mind sharing how to instal master branch? I'm having trouble building locally
