### ISSUE TITLE
not able to install with ember cli

### ISSUE THREAD

**Issue by figmentbml** [dockyard/ember-validations#241]
```
npm ERR! notarget No compatible version found: ember-validations@'>=2.0.0 <2.1.0'
npm ERR! notarget Valid install targets:
npm ERR! notarget ["0.0.0","2.0.0-alpha.1","2.0.0-alpha.2"]
npm ERR! notarget 
npm ERR! notarget This is most likely not a problem with npm itself.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
```

 DEBUG: -------------------------------
vendor.js:28585 DEBUG: Ember      : 1.8.1
vendor.js:28585 DEBUG: Ember Data : 1.0.0-beta.12
vendor.js:28585 DEBUG: Handlebars : 1.3.0
vendor.js:28585 DEBUG: jQuery     : 1.11.2
vendor.js:28585 DEBUG: -------------------------------

**Comment by bcardarella** [comment]
@figmentbml can you share what is in your `package.json`?

**Comment by figmentbml** [comment]
I removed "ember-validations": "~ 2.0.0" already

{
  "name": "notes",
  "version": "0.0.0",
  "description": "Small description for notes goes here",
  "private": true,
  "directories": {
    "doc": "doc",
    "test": "tests"
  },
  "scripts": {
    "start": "ember server",
    "build": "ember build",
    "test": "ember test"
  },
  "repository": "",
  "engines": {
    "node": ">= 0.10.0"
  },
  "author": "",
  "license": "MIT",
  "devDependencies": {
    "broccoli-asset-rev": "^2.0.0",
    "broccoli-ember-hbs-template-compiler": "^1.6.1",
    "ember-cli": "0.1.7",
    "ember-cli-6to5": "0.2.1",
    "ember-cli-content-security-policy": "0.3.0",
    "ember-cli-dependency-checker": "0.0.7",
    "ember-cli-ic-ajax": "0.1.1",
    "ember-cli-inject-live-reload": "^1.3.0",
    "ember-cli-qunit": "0.1.2",
    "ember-data": "1.0.0-beta.12",
    "ember-export-application-global": "^1.0.0",
    "ember-localstorage-adapter": "^0.5.0",
    "express": "^4.8.5",
    "glob": "^4.0.5"
  }
}

Beth Jaswa
______________________________
Developer  |  LinkedIn <http://www.linkedin.com/in/bethjaswa/>  |  GitHub
<https://github.com/figmentbml>  |  Twitter <https://twitter.com/figmentbml>

On Mon, Jan 26, 2015 at 12:46 PM, Brian Cardarella <notifications@github.com

**Comment by bcardarella** [comment]
I need to see what you had for ember-validations in order to help

**Comment by figmentbml** [comment]
This is what I had when when I got the error.

{
  "name": "notes",
  "version": "0.0.0",
  "description": "Small description for notes goes here",
  "private": true,
  "directories": {
    "doc": "doc",
    "test": "tests"
  },
  "scripts": {
    "start": "ember server",
    "build": "ember build",
    "test": "ember test"
  },
  "repository": "",
  "engines": {
    "node": ">= 0.10.0"
  },
  "author": "",
  "license": "MIT",
  "devDependencies": {
    "broccoli-asset-rev": "^2.0.0",
    "broccoli-ember-hbs-template-compiler": "^1.6.1",
    "ember-cli": "0.1.7",
    "ember-cli-6to5": "0.2.1",
    "ember-cli-content-security-policy": "0.3.0",
    "ember-cli-dependency-checker": "0.0.7",
    "ember-cli-ic-ajax": "0.1.1",
    "ember-cli-inject-live-reload": "^1.3.0",
    "ember-cli-qunit": "0.1.2",
    "ember-data": "1.0.0-beta.12",
    "ember-export-application-global": "^1.0.0",
    "ember-localstorage-adapter": "^0.5.0",
    "express": "^4.8.5",
    "glob": "^4.0.5",
"ember-validations": "~ 2.0.0"
  }
}

Beth Jaswa
______________________________
Developer  |  LinkedIn <http://www.linkedin.com/in/bethjaswa/>  |  GitHub
<https://github.com/figmentbml>  |  Twitter <https://twitter.com/figmentbml>

**Comment by bcardarella** [comment]
Ok, I see. The issue is that `2.0.0` is not released. You'll need `2.0.0-alpha.2`  https://www.npmjs.com/package/ember-validations

**Comment by bcardarella** [comment]
@figmentbml did this fix the problem?

**Comment by figmentbml** [comment]
Yes I was able to install it successfully.

Beth Jaswa
______________________________
Developer  |  LinkedIn <http://www.linkedin.com/in/bethjaswa/>  |  GitHub
<https://github.com/figmentbml>  |  Twitter <https://twitter.com/figmentbml>

On Wed, Jan 28, 2015 at 11:28 AM, Brian Cardarella <notifications@github.com

**Comment by bcardarella** [comment]
@figmentbml great to hear, thank you for following up
