### ISSUE TITLE
Version 1.0.0 never published to npm?

### ISSUE THREAD

**Issue by bradurani** [dockyard/ember-validations#243]
I've been using ember-validations 1.0.0 with success and am converting my app to use ember cli, but when I npm install I get 

```
npm ERR! notarget Valid install targets:
npm ERR! notarget ["0.0.0","2.0.0-alpha.1","2.0.0-alpha.2"]
```

Am I not supposed to be using 1.0.0? Is there a stable version I can use with ember cli?

Thanks

**Comment by bcardarella** [comment]
You'll want to add version `2.0.0-alpha.2` to `package.json`
