### ISSUE TITLE
[question] Disable "automatic" validation

### ISSUE THREAD

**Issue by bquenin** [dockyard/ember-validations#248]
Hi,

I'm using ember validation and it looks great. I have a form where I added some validations rules:

```js
export default Ember.Controller.extend(EmberValidations.Mixin, {
  actions: {
    signup: function () {
        ...
    }
  },
  validations: {
    firstName: {
      presence: true
    }
  }
});
```

I have the following template associated:

```mustache
<form {{action 'signup' on='submit'}}>
  <div {{bind-attr class=":form-group errors.firstName:has-error"}}>
    {{input value=firstName type="text" class="form-control" placeholder="First Name"}}
    {{#if errors.firstName }}
      <span class="help-block">{{format-error errors.firstName}}</span>
    {{/if}}
  </div>
  <button type="submit" class="btn btn-default"> Sign Up</button>
</form>
```
Everything works as excepted, but the problem is that the validation runs "on the fly" (i.e. when I display the form, it's already red and showing errors) and I'd like to trigger it only when the user press the submit button.

I haven't find any way to disable the "on the fly" validation. Can anyone point me to a way of achieving this?

Thanks

**Comment by bcardarella** [comment]
Please see: https://github.com/dockyard/ember-validations/wiki/automatic-validation
