### ISSUE TITLE
not able to create custom message 

### ISSUE THREAD

**Issue by vinodhrajamuralidharan** [DockYard/ember-validations#250]
```
validations: {
        name: {
            presence: {
                message:'Please enter your name'
            },
            numericality: {
                if :"requestSalary",
                lessThanOrEqualTo:130000,
                onlyInteger:true
            }
        },
        age: {
            presence: {
                message:'Please enter your age'
            },
            numericality: {
                if :"requestAge",
                lessThanOrEqualTo:25,
                onlyInteger:true
            }
        }
    }
```

For the above code  if I add a custom message for "lessThanOrEqualTo" using messages -> messages :{lessThanOrEqualTo : "please give a right value"}  is working fine but for onlyInteger is not working (messages :{lessThanOrEqualTo : "please give a right value",  onlyInteger : "Expecting some reasonable value"} or messages :{ onlyInteger : "Expecting some reasonable value"}

Could you please help me to fix this issue?

**Comment by bcardarella** [comment]
What version of the library are you using? We appear to be unit testing this: https://github.com/dockyard/ember-validations/blob/master/tests/unit/validators/local/numericality-test.js#L72-L88

**Comment by martndemus** [comment]
I am going to close this issue for now, feel free to reopen this issue if you feel like it's still relevant and we should take a look at it.
