### ISSUE TITLE
How to build?

### ISSUE THREAD

**Issue by samselikoff** [dockyard/ember-validations#251]
I followed the build instructions but I'm not sure where the actual lib is that I can pull into my project. I can't use the latest NPM release because of the cache fix that's in master.

In my the `dist` I see `vendor.js` and `dummy.js` which don't seem to be the lib.

**Comment by bcardarella** [comment]
That is expected as that is the output from building an ember-addon. It is intended to integrate with an ember app, the `dummy` app in this case. The relevant code is concat'ed into `vendor.js`.

**Comment by samselikoff** [comment]
Gotcha, so how do I get master into my project? Use a sha in the package.json entry?

**Comment by bcardarella** [comment]
You can use `2.0.0-alpha.2` as the version which is published to npm: https://www.npmjs.com/package/ember-validations

**Comment by samselikoff** [comment]
I don't believe that contains the fix for #234, which is why I need to upgrade

**Comment by bcardarella** [comment]
gotcha, you can pull from github but I cannot seem to find the documentation at the moment. And yes, I would link to a SHA
