### ISSUE TITLE
Clarify on nested "validatable objects".

### ISSUE THREAD

**Issue by duizendnegen** [dockyard/ember-validations#252]
In the README, I notice
> You define your validations as a JSON object. [..] If you pass true then the property itself will be seen as a validatable object.

Great! Say, I have a `route`, creating a new `flower` model, the `controller` should be able to defer its validations to the `model`, right? However, it doesn't quite work as I hoped. When `validate()` is called, the validations for the `model` run, but still, `"All OK"` appears in the output, even though `flower.name` is null.

```javascript
// controller/flower.js
import Ember from 'ember';
import EmberValidations from 'ember-validations';

export default Ember.Controller.extend(EmberValidations.Mixin, {
  // validation
  validations: {
    model: true
  },
  actions: {
	submit: function() {
	  var _this = this;
      this.validate().then(function() {
	    console.log("all ok");
      },
	  function() {
	    console.log(_this.get('errors'));
	  });
	}
  }
});
```
```javascript
// model/flower.js
import DS from 'ember-data';
import EmberValidations from 'ember-validations';

export default DS.Model.extend(EmberValidations.Mixin, {
  // validation
  validations: {
    name: {
      presence: true
    }
  },
  name: DS.attr('string')
  // name: null has the same behavior, leading me to believe it doesn't
  // have to do with DS.attr being a CP
});
```
```javascript
// route/flower.js
import Ember from 'ember';

export default Ember.Route.extend({
  model: function(params) {
	return this.store.createRecord('flower');
  }
});
```

How do I properly validate a nested property?
That being said, I am currently using Ember 1.8.0. Upgrading to 1.9.1 is on the roadmap, but is this behavior caused by the outdated dependency?

**Comment by danmcclain** [comment]
You shouldn't be calling `this.validate()`, that's kicked off automatically be the observers set up by ember-validations. In your submit, you should have something like the following

```js
if(this.get('isValid')) {
  console.log('all ok');
} else {
  console.log(this.get('errors'));
}

**Comment by duizendnegen** [comment]
Thanks for the pointer! I corrected that, makes a lot of sense.
However, still, `this.get('isValid')` shows `"all ok"` with my nested property. Any indications on why that is exactly?

**Comment by duizendnegen** [comment]
Thanks, that makes a lot of sense & solved it! Apparently the errors from `this.validate()` only contain those of the current object, not all underlying once. The `this.get('isValid')` property however is the right one to observe.
