### ISSUE TITLE
is it possible to include the validation code in models?

### ISSUE THREAD

**Issue by vinodhrajamuralidharan** [DockYard/ember-validations#253]
As, I am using lots of models in my application, there are the cases like, I have to include 2 more models in the route and I merge them using RSVP. I used previously objectcontroller and now I am changing it to controllers...  I'd like to replace my validations object from my controller to the models so that I don't have to use model.modelname.property.... 

Please tell me like is it possible to replace from the controllers to models?

**Comment by duizendnegen** [comment]
You can run validations as follows

(in your controller)
```javascript
yourFirstModel: booking: Ember.computed.alias("model.whateverTheFirstRsvpedThingIs"),
validations: {
   yourFirstModel: true,
   yourSecondModel: true
}
```

(in both of your to-be-validated models)
```javascript
import DS from 'ember-data';
import EmberValidations from 'ember-validations';

export default DS.Model.extend(EmberValidations.Mixin, {
  // validation
  validations: {
    someAttribute: {
      presence: true
    }
  }
  
  someAttribute: DS.attr('string')
});
```

**Comment by abobwhite** [comment]
It appears that this no longer works correctly. When calling ```validate``` on the controller using this method of ```model: true```, the promise always resolves, never rejects even though the model's validation fails. If I run ```validate``` on the model itself, the promise rejects correctly....

**Comment by abobwhite** [comment]
Bump. This is a major issue. Is there a new way to do this?

**Comment by bcardarella** [comment]
Hi @abobwhite sorry this went stale. There have been several tickets similar to this opened and I lose track of them. The official policy of this repo is that validations should be on the *context* not the model itself. Typically we see a desire to put validations on the model if devs are coming from another framework like Rails where validations are mixed into the model context. However, in the case of client side apps there is a very good case for not creating "global validation" graphs.

**Comment by abobwhite** [comment]
@bcardarella thanks for the quick follow-up. I don't have any background in rails, but I understand that you have developed a philosophy and want to have consistency. 

My main use case is not repeating validation when needing to validate a model or portions of a model from different controllers. I'm trying to stay DRY, here. Fortunately, I have workarounds for this. Whether this is a client-side app or a server-side app, our domain objects (models) should be able to tell you whether they are valid or not (except in cases when they are dependent on external factors, of course). The ```model: true``` option provides a great way to validate the underlying model (or other property) but still allowing controller-specific validations to merge with that lower-level model validation. The last thing I want to do is copy my length, presence, and other primitive validations around to each controller that needs that validation for the same model.

**Comment by bcardarella** [comment]
@abobwhite this is a good use case and I understand the desire to DRY things up. However, I suspect you can get the same benefit by extracting the validations into mixins and using those.

**Comment by abobwhite** [comment]
Hey @bcardarella. Any chance you could provide an example of how to best mixin the validations on a model? I've tried a few methods and I'm not sure there is a good way to keep the mixin validations for a particular standalone (i.e. just defining validations by property name and not having to hard-code ```model.<property>``` or something since it may not always be "the" model). If there is also a clean way to use custom validators per-model, also please let me know. Thanks!

**Comment by martndemus** [comment]
I am going to close this issue for now, feel free to reopen this issue if you feel like it's still relevant and we should take a look at it.
