### ISSUE TITLE
Transitioning back into an earlier accessed route doesn't re-initialize validators

### ISSUE THREAD

**Issue by duizendnegen** [DockYard/ember-validations#254]
In our case, the model function of the route returns a new record. The controller (a singleton) is then linked to that route, init is called and the validations are hooked up. If we transition out of that route and back into it again, init is not called a second time, and the validation is hooked to the old, un-used model provided by the route. See code, also notice the setupController function in my route where I forced the controller to init again.

I'm aware that validations rely heavily on init, but shouldn't they rely on setupController instead?

Route
```javascript
import Ember from 'ember';
import EmberValidations from 'ember-validations';

export default Ember.Controller.extend(EmberValidations.Mixin, {
  booking: Ember.computed.alias("model"),
  
  validations: {
    booking: true
  },
  actions: {
    submit: function() {
      if(this.get('isValid')) {
	    console.log("All OK");
	  } else {
	    console.log("Nope!");
	  }
    }
  }
});
```

Controller
```javascript
import Ember from 'ember';

export default Ember.Route.extend({
  model: function(params) {
    return this.get('store').createRecord('booking');
  },
  setupController: function(controller, model) {
    this._super(controller, model);
    // potentially re-initialize controller, to make validation working
    controller.init();
  }
});
```

Model
```javascript
import DS from 'ember-data';
import EmberValidations from 'ember-validations';

export default DS.Model.extend(EmberValidations.Mixin, {
  validations: {
    firstName: {
      presence: true
    },
    lastName: {
      presence: true
    }
  }
});
```

**Comment by martndemus** [comment]
I am going to close this issue for now, feel free to reopen this issue if you feel like it's still relevant and we should take a look at it.
