### ISSUE TITLE
Request: Add observer to conditional properties

### ISSUE THREAD

**Issue by green-arrow** [DockYard/ember-validations#256]
Currently, you can pass in a string property to an `if` or `unless` conditional. However, that validator is not run whenever the dependent property updates. It would be nice to have an option to allow the validator to be run again whenever a conditional property changes.

I am currently handling this in a custom validator. If you specify and `if` or `else` conditional with a string property, run `this.dependentValidationKeys.pushObject(condition);`

Any thoughts on the validity of this use case?

**Comment by bcardarella** [comment]
this is being planned out right now. Basically when any of the values for a validation changes, the validator should recalculate

**Comment by green-arrow** [comment]
Awesome, glad that's in the pipeline

**Comment by davidpike7** [comment]
Hey @green-arrow could you give an example of how you handled this? I'm running into the same issue.

Cheers

**Comment by davidpike7** [comment]
@bcardarella Any indication for when this one will be resolved? 

Happy to help out where I can

**Comment by sweetroll** [comment]
+1, same issue here.

**Comment by green-arrow** [comment]
@davidpike7 the solution I came up with was for a `PresenceValidator` that listened for changes to the property it was dependent on.

`app/validators/local/conditional-presence.js`

```javascript
import Ember from 'ember';
import PresenceValidator from 'ember-validations/validators/local/presence';

export default PresenceValidator.extend({
  init: function() {
    this._super.apply(this, arguments);

    var condition;

    if(this.conditionals) {
      condition = this.conditionals['if'] || this.conditionals['unless'];
    }

    Ember.assert('You must specify "if" or "unless" in the options for the conditional presence validator.', !!condition);

    if(Ember.typeOf(condition) === 'string') {
      // Condition based on another property. Make sure to watch that property
      this.dependentValidationKeys.pushObject(condition);
    }
  }
});
```

**Comment by davidpike7** [comment]
Thanks @greenarrow. That works great.

I've just attempted to create a conditional numericality validator using the code you've provided but I don't fully understand how it works. What would need to be tweaked in your presence validator to get it working?

**Comment by green-arrow** [comment]
@davidpike7: I believe that there is already a numeric validator provided with ember-validations, you could use that as your base instead of `PresenceValidator` and work from there.

**Comment by martndemus** [comment]
I am going to close this issue for now, feel free to reopen this issue if you feel like it's still relevant and we should take a look at it.
