### ISSUE TITLE
Couldn't find service:validations in needs for QUnit (controllers)

### ISSUE THREAD

**Issue by jniechcial** [DockYard/ember-validations#258]
I was making tests for controllers using guidelines in `README`, but it turned out that `'service:validations'` couldn't be found. I am not sure if it is not supported anymore, but with my versions of ember-cli and QUnit I had to remove it. 

Could you consider changing `README` (as it took some time to find out what is going on) if it is common for other users?

My versions:
* `ember-cli 0.1.15`
* `ember-cli-qunit 0.3.7`
* `qunit 1.17.1`
* `ember 1.9.0`

**Comment by khanhhua** [comment]
It's been a YEAR since @jniechcial posted the issue. I have run some related issue.

Code setup:
```
moduleFor('controller:login', 'Unit | Controller | Login', {
  unit: true,
  needs: [
    'controller:application',
    'ember-validations@validator:local/presence'
  ]
});
```

Error stack:
```
Died on test #2     at test (http://localhost:4200/assets/test-support.js:1644:11)
    at http://localhost:4200/assets/tests.js:2177:24
    at mod.state (http://localhost:4200/assets/vendor.js:160:29)
    at tryFinally (http://localhost:4200/assets/vendor.js:40:14)
    at requireModule (http://localhost:4200/assets/vendor.js:158:5)
    at Object.TestLoader.require (http://localhost:4200/assets/test-loader.js:29:9)
    at Object.TestLoader.loadModules (http://localhost:4200/assets/test-loader.js:21:18): <(unknown mixin):ember283>
```

**Comment by martndemus** [comment]
I am going to close this issue for now, feel free to reopen this issue if you feel like it's still relevant and we should take a look at it.
