### ISSUE TITLE
Failing "presence" validation when the property is a typeof "object"

### ISSUE THREAD

**Issue by bosschuyler** [dockyard/ember-validations#261]
I have validation checking for the existence of an object at the end of one of my forms.  I added console logging to the Ember.Validations for the "presence" validator to give me details about it's check.

This is what I'm logging:
   
     console.log(this.model);
     console.log(this.property);
     console.log(get(this.model, this.property));
     console.log(typeof get(this.model, this.property));
     console.log(Ember.isBlank(get(this.model, this.property)));  
     console.log(Ember.isEmpty(get(this.model, this.property)));

Here's what I get from the logging:

     r {container: i, errors: r, dependentValidationKeys: Object, validators: (...), colors: Array[1]…}
     product
     r {container: i, errors: r, dependentValidationKeys: Object, validators: Array[8], original: r…}
     object
     true
     true

The odd thing is it only happens on some of my products.  It almost seems like an issue with the Ember.isEmpty function.  it's returning false even though the object exists.

**Comment by danmcclain** [comment]
Could you include your validation definitions on your controller (I'm assuming it's on your controller)

**Comment by bcardarella** [comment]
We're just using Ember's `isBlank` function here. We'd need to know more about the object that is being checked

**Comment by bosschuyler** [comment]
I created my own model system for interfacing with my API backend, The validations are actually on my custom model.  Here's what that looks like:

    validations: {
        title: {
            presence: {
                message: 'Title must not be blank',
            },
            length: {
                minimum: 3,
                messages: {
                    tooShort: 'Title should be more than 3 characters'
                }
            }
        },
        product: {
            presence: {
                message: 'Product must not be blank'
            }
        },
        sku: {
            presence: {
                message: 'Sku must not be blank'
            }
        },
        size: {
            presence: {
                message: 'Size must not be blank'
            }
        },
        active: {
            presence: {
                message: 'Active must be selected'
            }
        },
        images: {
            array: {
                alsoWatch: 'images.[]',
                message: 'Must have at least one image'
            }
        },
        mpn: {
            length: {
                maximum: 32,
                message: {
                    tooLong: 'MPN cannot be longer than 32 characters'
                }
            }
        }
    },

**Comment by bosschuyler** [comment]
yea it seems the isEmpty check is saying it's empty,  I guess I was wondering if anyone knew how "object" types were checked for being empty or not?

**Comment by danmcclain** [comment]
Here is the definition of `isEmpty`: https://github.com/emberjs/ember.js/blob/master/packages/ember-metal/lib/is_empty.js

**Comment by bcardarella** [comment]
we're using isBlank and not isEmpty

**Comment by danmcclain** [comment]
D'oh, thanks @bcardarella, Here is the `isBlank` definition: https://github.com/emberjs/ember.js/blob/master/packages/ember-metal/lib/is_blank.js

**Comment by bosschuyler** [comment]
My "presence.js" shows this:

    if (Ember.isEmpty(get(this.model, this.property))) {
         this.errors.pushObject(this.options.message);
    }

Am I out of date?  either way though, I logged out isBlank and that fails as well.

**Comment by bcardarella** [comment]
@bosschuyler which version of the library are you using?

**Comment by bosschuyler** [comment]
looks like my package.json has ember validations set to: 2.0.0-alpha.1

**Comment by bcardarella** [comment]
Can you try `2.0.0-alpha.2` ?

**Comment by bosschuyler** [comment]
certainly.  updates are always good :), let me update and I'll report back.

**Comment by bosschuyler** [comment]
yea looks like it's still failing.  I'm thinking this may be an Ember issue and nothing to do with you guys.  I may have to log through the isEmpty function and see if I can figure out what it doesn't like about it.

**Comment by bcardarella** [comment]
@bosschuyler if there is anyway you can recreate this in a simple example app and share it I'd be happy to diagnose it

**Comment by bosschuyler** [comment]
yea I can see if I can reproduce this but this is the first time I've ever seen it and it happens only with products I've created recently.  So the nature of the complexity may be the reason there is an issue.  I'm going to have to keep tracking this down.  The links for the Ember code base will help.  Thanks for pointing me in the right direction.  If I find something I'll report back.

**Comment by bosschuyler** [comment]
I FIGURED IT OUT!

**Comment by bcardarella** [comment]
Do share

**Comment by bosschuyler** [comment]
here is where the validation fails for me:

    if (typeof obj.length === 'number' && objectType !== 'function') {
        return !obj.length;
    }

I have a property called length for my products.  in the instance where I don't have a "length" for a product it is set to 0 (probably should have been null) but even still it's not going to solve the issue of using a reserved word since properties are mixed in with reserved properties.  I have to figure out a different solution to using length of a product.  might have to change my naming convention.

**Comment by bcardarella** [comment]
Gotcha, glad to see its resolved. I'll close this issue.

**Comment by bosschuyler** [comment]
yea I'm glad I figured it out finally.  Reserved keys in JS are kinda wonky, I feel like they should use some sort of underscore notion for keys that are internal to the function of JS.  There's so many words that you'd want to use for variable names that you can't cause of that convention.  Not a discussion for here, but had to rant.
