### ISSUE TITLE
Docs and build version hosted on builds.dockyard.com out of sync?

### ISSUE THREAD

**Issue by saslanidis** [DockYard/ember-validations#262]
I have no ember cli project, so I would like to consume ember-validations from here http://builds.dockyard.com/

Can it be, that the current documentation do not match the version build on the server?
For example, the property "dependentValidationKeys" mentioned in the docs (https://github.com/dockyard/ember-validations#creating) in not present in the build version, its only "_dependentValidationKeys".

Now I have the feeling, that the build version is not up to date.

By the way it makes no difference if I choose
http://builds.dockyard.com.s3.amazonaws.com/ember-validations/ember-validations-latest.js or
http://builds.dockyard.com.s3.amazonaws.com/ember-validations/release/ember-validations.js

Thank you

**Comment by martndemus** [comment]
I am going to close this issue for now, feel free to reopen this issue if you feel like it's still relevant and we should take a look at it.
