### ISSUE TITLE
Trouble getting started, docs out of date..?

### ISSUE THREAD

**Issue by CoenWarmer** [DockYard/ember-validations#263]
I am having some trouble getting started with ember-validations.

I am not using the Ember CLI as referenced in the docs, so I have downloaded a compiled ember-validations.js from http://builds.dockyard.com/ and have included ember-validations.js in my apps js file.

The docs now say to pass the validations.mixin into a controller:

So I'm using:

```javascript
App.MemberaddController = App.FamilyController.extend(EmberValidations.Mixin,{
    needs: ["family","notifications"],
    familyController: Em.computed.alias('controllers.family'),
    notifications: Em.computed.alias('controllers.notifications'),

    validations: {
        firstname: {
            presence: true,
            presence : {message: 'can not be empty'}
        }
    },
    <etc...>
}
```

However in the browser I'm seeing

```
Uncaught ReferenceError: EmberValidations is not defined
```

Looking at the ember-validations.js I can see the mixin file being referenced as Ember.Validations.Mixin.

So when I pass that to my controller, like

```javascript
App.MemberaddController = App.FamilyController.extend(Ember.Validations.Mixin,{
```

I'm seeing:

```
Error while processing route: memberadd Cannot read property 'invoke' of undefined TypeError: Cannot read property 'invoke' of undefined
```

In the ember-validations.js file at the _validate function.

What am I doing wrong here?

**Comment by jordanthornquest** [comment]
I am having the same issue, here.
```
Error while processing route: memberadd Cannot read property 'invoke' of undefined TypeError: Cannot read property 'invoke' of undefined
```

**Comment by martndemus** [comment]
I am going to close this issue for now, feel free to reopen this issue if you feel like it's still relevant and we should take a look at it.
