### ISSUE TITLE
Is there way to remove debounce of error message, while user is typing?

### ISSUE THREAD

**Issue by glagola** [dockyard/ember-validations#265]
Hi, is there way to remove debounce of error messages, while user is typing? 

Here is the problem description: I have string length validator with minimum of 3 chars length, when I start typing it  shows me the error immediately, until I've typed at least 3 chars. 

IMHO, this behaviour is not user-friendly (It is look like user is already guilty, while he even not finishes input). I think validation should run when field looses focus like, e.g. [jquery.validation plugin does](http://jqueryvalidation.org/files/demo/).

May be I'm wrong and miss something, can you help me figure out how to achieve debouncing of user input validation?

Thank you!

P.S. sorry for my English

**Comment by bcardarella** [comment]
https://github.com/dockyard/ember-validations/wiki/automatic-validation

**Comment by glagola** [comment]
Thank you, you help me reconsider my view of input validation with emberjs!
