### ISSUE TITLE
Looks like validations are not actually firing?

### ISSUE THREAD

**Issue by constantm** [dockyard/ember-validations#271]
It looks like my validations aren't firing correctly as the `isValid` always returns true. I'm not really sure if I'm use the library correctly. My client new controller looks as follows:

```
//app/controllers/clients/new.js

import Ember from 'ember';
import EmberValidations from 'ember-validations';

export default Ember.Controller.extend(EmberValidations.Mixin, {
  validations: {
    clientName: {
      presence: true,
      length: { minimum: 5 }
    },
    clientEmail: {
      presence: true,
      length: { minimum: 5 }
    }
  },

  actions: {
    saveClient: function(){
      var newClient = this.store.createRecord('client', {
          clientName: this.get('clientName'),
          clientEmail: this.get('clientEmail')
      });
      newClient.save();
      this.setProperties({
          clientName: '',
          clientEmail: ''
      });
    }
  }
});
```

I use form-master-2000 and my client/new template looks like follows:

```
// app/templates/clients/new.hbs

{{#fm-form action='saveClient'}}
	{{fm-field type='text' value=clientName label='Client Name' errors=model.errors.clientName}}
	{{fm-field type='text' value=clientEmail label='Client Email' errors=model.errors.clientEmail}}
	{{fm-submit value='Save Client'}}
{{/fm-form}}
```

When adding in a `debugger()` after the object creation in `actions`, `newClient.get('isValid')` always returns true. I'm trying to use the library with `form-master-2000`. What am I doing wrong here?

**Comment by bcardarella** [comment]
@constantm you are looking at ember-data's `isValid` flag in this case because you are looking at the `newClient` instance and not the controller's.

**Comment by constantm** [comment]
Aaah okay. So, so the problem is that it's still not working though. Could you please let me know what I'm doing wrong in the above as the documentation isn't very clear.

**Comment by bcardarella** [comment]
Can you describe what it is you're trying to accomplish?

**Comment by constantm** [comment]
I'm trying to get validation to work on the client object. As far as I understand the validation updates as the object changes, unlike in Rails where is validates when the object is saved. Adding the validation in the way I have done doesn't do anything, so I'm probably missing something or I have the code in the wrong place. What I'm trying to accomplish is to simply add some validation on the client/new template. I'm also trying to understand why the object still saves when validation should fail.

**Comment by bcardarella** [comment]
I'm not familiar with fm-2000 but I suspect you will need to to `controller.errors.first_name` instead of `model.errors.first_name`

**Comment by constantm** [comment]
Ah that does the trick, thanks!
