### ISSUE TITLE
How to use with a non-CLI Ember project?

### ISSUE THREAD

**Issue by GeoffreyBooth** [DockYard/ember-validations#279]
I have an Ember 1.11.1 app. I tried porting my app to Ember-CLI, but I reverted back because of CLI’s [lack of support for source maps](https://github.com/kimroen/ember-cli-coffeescript/issues/7). Hopefully when CLI is more developed I’ll try porting over again.

In the meantime, I want to use ember-validations with my app. As far as I can tell, the only way to use ember-validations with a non-CLI app is to use the 1.0.0 build that I get from `bower install ember-validations`. Unfortunately, I'm encountering #268, which isn’t surprising since my ember-validations build is six months old. I’d like to use the latest build, or #277, but I don’t see how to use the current 2.x code in a non-CLI project. Is that possible? Or is there a way to make a non-CLI-style build from the latest code?

**Comment by rwjblue** [comment]
Ember CLI supports source maps fairly well. That issue you referenced was regarding coffeescript source maps, not ember-cli itself.

You could try using [ember-giftwrap](https://github.com/ef4/ember-giftwrap) to use this addon in a globals based project...

**Comment by DiegeticShadow** [comment]
Yes, I meant CoffeeScript source maps, thanks for correcting me.

Thanks for the suggestion regarding ember-giftwrap. It’s only a week old and in “alpha quality” according to its readme, so perhaps not quite ready for prime time. But I guess if that’s what you’re proposing, that must mean there’s no easy way to include ember-validations 2.x into a project via bower or npm or browserify or as a standalone library.

I guess this is just a frustrating period to be developing in Ember: Ember CLI isn’t quite production-ready (at least for me), yet many plugin developers like Dockyard have already abandoned globals-based Ember. Hopefully sometime soon either Ember CLI or ember-giftwrap will mature enough to close the gap.

**Comment by martndemus** [comment]
I am going to close this issue for now, feel free to reopen this issue if you feel like it's still relevant and we should take a look at it.

**Comment by GeoffreyBooth** [comment]
I was able to get this to work using ember-giftwrap. Thanks.
