### ISSUE TITLE
How do you specify validations on extended object ?

### ISSUE THREAD

**Issue by Hanastaroth** [dockyard/ember-validations#281]
Hi, 

I have two objects (ember data model). 
The first one has validations defined on some of its properties. 

The second one extends the first and I need to add some validations on some of the specific properties. 

How do I do this ? 
I can't reopen the object as I will completly erase the super validations, but I can't find a way to add my specific validations to the existing ones (without duplicating). 

Any suggestions ? 

Thanks in advance.

**Comment by Hanastaroth** [comment]
A solution has been found, but if you have any better way I'll be glad. 

Here is the solution: 

```js
MyObject = MySuperObject.extend({
  someAttribute: DS.attr('string');
});

MyObject.reopen({
  init: function() {
    var validations = this.get('validations');
    validations.someAttribute = {
      presence: true
    };
    this._super();
  }
});
```

**Comment by danmcclain** [comment]
What if you add the property `mergedProperties: ['validations']` to the super object? That may work

**Comment by Hanastaroth** [comment]
I'll try that tomorrow. Thanks for the suggestion.

**Comment by Hanastaroth** [comment]
@danmcclain Thanks for your help ! That works perfectly.
