### ISSUE TITLE
[Question] Using Custom Validation in Ember Cli Project

### ISSUE THREAD

**Issue by shiv86** [DockYard/ember-validations#283]
Say for example in my ember cli project I have created a custom validator called **alwayserror** which just returns back the error string. How do I  add this to the validations defined in my Model.js ?

```javascript
my-app/app/validators/local/alwayserror

export default Base.extend({
  call: function() {
      this.errors.pushObject("error occurred");
  }
});

**Comment by martndemus** [comment]
I am going to close this issue for now, feel free to reopen this issue if you feel like it's still relevant and we should take a look at it.
