### ISSUE TITLE
Async custom validator?

### ISSUE THREAD

**Issue by samselikoff** [dockyard/ember-validations#288]
I saw 'remote validator' in the Readme but can't figure out if my custom validators can return promises.

I'm adding a validation to my `Question` model, which has many `Answer`s. It looks like this:

```js
answers: {
  inline: EmberValidations.validator(function() {
    var question = this.model;
    var answers = question.get('answers');

    return Ember.RSVP.all(answers.invoke('validate'))
      .finally(() => {
        if (answers.mapBy('isValid').contains(false)) {
          return "One of this question's answers is invalid";
        }
      });
  })
}
```

I essentially want `question.get('isValid')` to return `false` if any of its answers are invalid. When I use the code above, the error message is just `[Object object]`, which I'm assuming is the promise itself.

Is something like this possible?

**Comment by bcardarella** [comment]
The `validator` helper function is only intended to return a string (error message) or `undefined` and it will handle everything else. You might want to try:

```javascript
answers: {
  inline: EmberValiadtions.validator(function() {
    var question = this.model;
    var answers = question.get('answers');

    if (answers.mapBy('isValid').contains(false)) {
      return "One of this question's answers is invalid";
    }
  }
}
```
