### ISSUE TITLE
validate is not a function

### ISSUE THREAD

**Issue by amk221** [DockYard/ember-validations#291]
* I built ember-validations, created a simple object with EmberValidations mixed-in and it works fine.
* I then created a fresh ember-cli project and used the same code, but it fails with `.validate is not a function`

No idea why, or where to start debugging.  (Ember 1.11.1 and 2.0.0-alpha.3 in both cases)

**Comment by NuckChorris** [comment]
I ran into the same issue just now and solved it by mixing in `EmberValidations.Mixin` — looks like they accidentally exported the wrong object

**Comment by johnbk** [comment]
Faced the same issue - solved it by mixing in ``` EmberValidations.Mixin``` 
We are on Ember 1.11.1 and CLI 0.2.3 - Are the docs up to date?

**Comment by danmcclain** [comment]
The readme on master reflects changes on the master branch, which uses the default export, not `.Mixin` like the previous versions

**Comment by albertpak** [comment]
added `"ember-validations": "~ 2.0.0"` to `package.json`, ran npm install, bower install , and get an error:

```
npm ERR! notarget No compatible version found: ember-validations@'>=2.0.0 <2.1.0'
npm ERR! notarget Valid install targets:
npm ERR! notarget ["0.0.0","2.0.0-alpha.1","2.0.0-alpha.2","2.0.0-alpha.3"]
npm ERR! notarget
npm ERR! notarget This is most likely not a problem with npm itself.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
```

**Comment by NuckChorris** [comment]
@albertpak for the NPM error, there's no 2.0.0 release yet, only alphas. `~ 2.0.0` doesn't match alphas

**Comment by martndemus** [comment]
I am going to close this issue for now, feel free to reopen this issue if you feel like it's still relevant and we should take a look at it.
