### ISSUE TITLE
`isValid` read-only during testing for Ember 1.11

### ISSUE THREAD

**Issue by YoranBrondsema** [dockyard/ember-validations#292]
I have a model `ModelA` which has a nested model `NestedModelB`. `ModelA` looks like this:

````
export default DS.Model.extend(EmberValidations.Mixin, {
  /* Associations */
  nestedModelB: DS.belongsTo('nestedModelB'),

  /* Validations */
  isValid: function() {
    return this._super() && this.get('nestedModelB.isValid');
  }.property('validators.@each.isValid', 'nestedModelB.isValid')
});
````

So every instance of `ModelA` is valid iff it is itself valid and its nested models are valid. I have a unit test for `ModelA` that tests this:

````
test('isValid', function() {
  Ember.run(function() {
    // Make sure that modelA is valid in itself
    const modelA = this.subject();
    const nestedModelB = this.store().createRecord('nestedModelB', { modelA: modelA });

    nestedModelB.set('isValid', false);
    ok(! modelA.get('isValid'));

    nestedModelB.set('isValid', true);
    ok(modelA.get('isValid'));
  });
});
````

This worked in Ember.js up until 1.10. However, after upgrading to Ember 1.11, it says `cannot set read-only property isValid` on `nestedModelB`.

I searched the `ember-validations` repository for the keyword `readOnly` but there's no match. So I'm not too sure how this `isValid` property becomes `readOnly`.

**Comment by raycohen** [comment]
DS.Model's `isValid` property is now [readOnly](https://github.com/emberjs/data/blob/9c83224bc0b5935adfb6f3a68290348e2d0dea3f/packages/ember-data/lib/system/model/model.js#L215)

**Comment by YoranBrondsema** [comment]
@raycohen I wasn't aware that it was in Ember Data, not in ember-validations. Thanks!

**Comment by raycohen** [comment]
If you use the ember validations mixin with your nestedModelB's `DS.Model.extend` you will get the `isValid` CP from this project and it should not error when using `nestedModelB.set('isValid', ...)`
