### ISSUE TITLE
Validations not working

### ISSUE THREAD

**Issue by ZackMattor** [DockYard/ember-validations#293]
I've been trying to get ember-validations working for the better part of today and i'm having no luck at all. I was originally on ember 1.11.1 but i noticed there were some issues there so I rolled back. Now I think it might be an ember-data issue?

I guess what i'm looking for is if i'm doing anything noticeably wrong then i might have to play with my versions a bit more...

https://gist.github.com/Criten/b3be935c9585a9aa404b

**Comment by jamesarosen** [comment]
What happens if you try `.extend(EmberValidations.Mixin)`? See #299

**Comment by Criten** [comment]
I remember trying that because i was diggign through the source and noticed that.. But I'm pretty sure it still wasn't working. I have since moved onto a self-rolled validation scheme, but I will probably revisit it to try it again soon.

**Comment by danmcclain** [comment]
https://github.com/dockyard/ember-validations/issues/291#issuecomment-100498781

**Comment by betasve** [comment]
Not working for me as well. I am using: 
- Ember-CLI 0.2.3
- Ember 1.11.1
- There were compatibility errors when trying to install ember-validations ~2.0.0, as per README page, so I've installed 2.0.0-alpha.3
- Imported EmberValidations - #validate() not defined
- tried to use EmberValidations.Mixin - #validate() not defined as well;

**Comment by anthonycollini** [comment]
I have the same issues, not matter what I try, this addon doesn't work for me. Same issues as above:

- `Uncaught TypeError: this.get(...).validate is not a function` when I try to manually call `validate`
- No errors are added even though I have the mixin and validations defined.

It might help if there was a screencast on how to properly set this up in a controller and how to call .validate before attempting to save your model.

**Comment by saarangsoltani** [comment]
the FIX is to correctly extend the object that needs validation 
```javascript
import EmberValidations from 'ember-validations';
export default DS.Model.extend(EmberValidations.Mixin, {
   age: DS.attr('number'),
   validations: {
      age: { presence: true }
   }
}
```
notice the `.Mixin` thing. This is a recent change to the API and README should be updated soon

**Comment by walter** [comment]
When I upgraded to Ember 1.13.5 and then ember-validations 2.0.0-alpha.4 from ember-validations 2.0.0-alpha.3, I actually had the opposite solution. I had to remove the `.Mixin` to get things to come right.

**Comment by walter** [comment]
I may have spoken too soon. In my addon, removing the `.Mixin` allowed tests to pass, but then when using the addon, my application's tests blew up. Downgrading to alpha.3 for now.

**Comment by martndemus** [comment]
I am going to close this issue for now, feel free to reopen this issue if you feel like it's still relevant and we should take a look at it.
