### ISSUE TITLE
What is the difference between local and remote validators? 

### ISSUE THREAD

**Issue by szachara** [dockyard/ember-validations#295]
I read and searched whole repo and of course mixing.js code, but I don't see any difference. 

Thank you for advice.

**Comment by bcardarella** [comment]
@szachara there are situations where you might have a validator that works both locally and remotely. In that case you want the local validator to work first then the remote validator. Hence the reason for the two difference name spaces

**Comment by szachara** [comment]
Ok thanks, may be this explanation could be pasted into the README.md for
other users.

Silver Zachara
Dňa 6.5.2015 7:00 PM používateľ "Brian Cardarella" <notifications@github.com>
napísal:
