### ISSUE TITLE
Error using EmberValidations.Mixin

### ISSUE THREAD

**Issue by quaertym** [dockyard/ember-validations#296]
I got the following error and have no idea why. Any help is appreciated.
```
Uncaught Error: Assertion Failed: Expected hash or Mixin instance, got [object Undefined]
```

This is how I use it with a controller:
```
import Ember from 'ember';
import EmberValidations from 'ember-validations';
export default Ember.ObjectController.extend(EmberValidations.Mixin, {

});
```

**Comment by danmcclain** [comment]
You mix in `EmberValidations` directly now: https://github.com/dockyard/ember-validations#usage (depending on your version)

**Comment by quaertym** [comment]
@danmcclain Thanks, that was it :+1:

**Comment by kenips** [comment]
:+1: wished there was a bigger warning going from alpha.3 to alpha.4!!

**Comment by bcardarella** [comment]
@kenips did you read the upgrade guide that has been here? https://github.com/dockyard/ember-validations/blob/master/UPGRADE.md

**Comment by kenips** [comment]
Ah. Nice. That's a great place to start documenting these breaking changes :).
