### ISSUE TITLE
Mutually Exclusive fields

### ISSUE THREAD

**Issue by jackmatt2** [DockYard/ember-validations#301]
Is there a way to to ensure only one of two fields on a model have a value?  I have tried using the 'if' and custom 'inline' validators but can't get it working.

Basically I need an xor:

```javascript
model.get('field1') xor model.get('field2')
```

**Comment by martndemus** [comment]
I am going to close this issue for now, feel free to reopen this issue if you feel like it's still relevant and we should take a look at it.
