### ISSUE TITLE
Add has validation occured property

### ISSUE THREAD

**Issue by QuantumInformation** [dockyard/ember-validations#303]
I frequently have to show validation icons in templates based on the state of a validation property which works fine. However I often have to create addition validation properties in order to hide both the valid and non valid icon in the form. Can we also have something like a 'hasMyFooPropBeenValidated' available for use in the templates?

**Comment by bcardarella** [comment]
You should always assume that the validators have run

**Comment by QuantumInformation** [comment]
@bcardarella ok thanks)

btw is this lib compatible with ember cli 0.2.5 and pods? I imported it into a pods controller it it never seems to have been setup: https://github.com/dockyard/ember-validations/issues/302#issuecomment-103094236.

**Comment by bcardarella** [comment]
@QuantumInformation the README is ahead of the current release version. Please use the README on npm or you can go to the versioned tag of the README
