### ISSUE TITLE
Uncaught TypeError: t[m] is not a function

### ISSUE THREAD

**Issue by QuantumInformation** [DockYard/ember-validations#304]
I am getting this error when doing this.validate():

`Uncaught TypeError: t[m] is not a function`
 

```js
 isFormInValid: function () {
    var self = this;
    this.validate().then(function() {
      // all validations pass
      self.set("isFormInValid", false);
      return;

    }).catch(function() {
      // any validations fail
      self.set("isFormInValid", true);
      return;

    }).finally(function() {
      // all validations complete
      // regardless of isValid state
      return;
    });
  }.observes('age','firstName'),
```

The rest of my validation stuff works fine like:
```js 
isFirstNameValid: function () {
    console.log("firstName valid");
    return !this.get("errors.firstName.length");
  }.property('firstName'),

**Comment by danmcclain** [comment]
Form validation is run automatically, you should not be calling `validate` manually

With the addon, it provides `isValid` & `isInvalid` for the object in which the validations are defined

**Comment by QuantumInformation** [comment]
@danmcclain thanks, can I assign this controller property (isInvalid) like so in my template?

`disabled="{{isInvalid}}`

**Comment by QuantumInformation** [comment]
I decided to do this is I couldn't us isInvalid on my template:
```js
  isFormInvalid: function () {
    return this.get("errors.age.length") || this.get("errors.firstName.length");
  }.property('age', 'firstName'),

```
`                <button id="submit" class="btn btn-success pull-right" {{action "submit" firstName age}} disabled="{{isFormInvalid}}">Submit
`

**Comment by martndemus** [comment]
I am going to close this issue for now, feel free to reopen this issue if you feel like it's still relevant and we should take a look at it.
