### ISSUE TITLE
errors object is not iterable

### ISSUE THREAD

**Issue by benlieb** [DockYard/ember-validations#310]
It  would be nice to have the errors object iterable. Is there an implementation limitation that precludes this?

Right now I'm having to suck the objects myself, via duplicated (once in validations:{}) hard-coded properties: 

collectionItemErrors.getProperties("collectionItemImage", "authors", "publisher", "title", "publishedOn", "copyright", "credit");

**Comment by gkaran** [comment]
From what I understand you want to get all the error messages? If that is the case here is a way is easier to yours and keys agnostic:

In your component/controller/etc:

    Object.keys(x).map(key => x[key]).reduce((a,b) => a.concat(b), []);

In your template:

    {{#each-in errors as |field fieldErrors|}}
      {{#each fieldErrors as |fieldError|}}
        {{!-- Do something with the fieldError here --}}
      {{/each}}
    {{/each-in}}

Beware that `each-in` does not refresh automatically when errors change. Personally I ended up creating a simple component with the template solution when I want to display all the validations errors.

**Comment by martndemus** [comment]
I am going to close this issue for now, feel free to reopen this issue if you feel like it's still relevant and we should take a look at it.
