### ISSUE TITLE
ie strict mode

### ISSUE THREAD

**Issue by koryteg** [dockyard/ember-validations#311]
I am getting an error in IE, `multiple definitions of a property is not allowed in strict mode` 

the line it errrors on looks like this: 

``` coffeescript
presence: true
presence:
  message: 'my custom message'
```
not sure the best way to handle this. but essentially declaring `presence` as a property twice doesn't look like it is going to work.

**Comment by tahniyat-devacc** [comment]
Hey guys. Any update on this ? I am getting same error on IE 11.

**Comment by bcardarella** [comment]
If you pass an object to `presence` is is assumed true:

```js
presence: true
```

is equal to

```js
presence: {
  message: 'my custom message'
}
```

but the 2nd allows you to override the message.

**Comment by bcardarella** [comment]
Sorry I missed this when it originally opened.
