### ISSUE TITLE
Access all outstanding errors from the form

### ISSUE THREAD

**Issue by jme783** [dockyard/ember-validations#314]
As my form in my application takes up a good amount of vertical space, I'm trying to add a section to my form beneath the submit button that will tell the user exactly which validations are still failing, kind of like 
this:
![screen shot 2015-06-07 at 9 59 12 pm](https://cloud.githubusercontent.com/assets/4605360/8028359/7af471de-0d60-11e5-8055-31ef7f728d76.png)

 This would be _in addition_ to the error messages that appear next to the individual inputs. Is there any easy way to grab a list of all the outstanding failed validations? I was looking at `this.errors` in the controller, however, there doesn't seem to be any aggregate object that gives me an array of all the outstanding errors. The only way to get this information seems to be accessing each individual validation property by its unique name, like this `errors.get('buyerFirstName')`.

Is there an easier way? Thank you!

**Comment by bcardarella** [comment]
From a usability and form conversion perspective this approach has been proven to not be optimal. You can see some of that research here: http://alistapart.com/article/inline-validation-in-web-forms

That being said, we should strive to be as flexible as possible with ember-validations. You can probably just add something like the `errorArray` CP I've added here: http://emberjs.jsbin.com/kufefenufa/1/edit?html,js

**Comment by jme783** [comment]
Thanks @bcardarella for the great answer!

**Comment by bcardarella** [comment]
The longer term solution would be for us to make the `errors` object Enumerable. I've marked this as a 2.0 blocer
