### ISSUE TITLE
How to load validations in acceptance tests

### ISSUE THREAD

**Issue by Fryie** [DockYard/ember-validations#315]
It seems that during testing, validations are not loaded.  When the tests are run, the console just logs "WARNING: Could not find the "presence" validator.". I see there are examples in the documentation on how to inject validations into unit tests, but nothing specific for acceptance tests. I really don't understand Ember's dependency injection mechanism well yet, so any help would be appreciated.

NB: I'm using ember-cli.

**Comment by Fryie** [comment]
FWIW, it works if I specificy the validators in the controller:
```{javascript}
export default Ember.Controller.extend(EmberValidations.Mixin, {
  needs: ['ember-validations@validator:local/presence'],
  ...
});
```

it still seems strange, because that's not necessary outside of test mode.

**Comment by martndemus** [comment]
I am going to close this issue for now, feel free to reopen this issue if you feel like it's still relevant and we should take a look at it.
