### ISSUE TITLE
'isFinal' not updating after validations are satisfied.

### ISSUE THREAD

**Issue by MatthewRDodds** [DockYard/ember-validations#316]
I have a situation where even after all validations are satisfied, the `isValid` property returns `false`.

An example model:

```coffeescript
`import EmberValidations from 'ember-validations'`

Car = DS.Model.extend EmberValidations.Mixin,
  hasWheels: DS.attr('boolean')

  isViableCar: (->
    return @get('hasWheels')
  ).property('hasWheels')

  validations:
    hasWheels:
      acceptance: true
    isViableCar:
      acceptance: true

`export default Car`
```

In my test I create the car, set `hasWheels` to false and validation fails as expected:

```javascript
car.errors
Class {
  hasWheels: Array[1]
  isViableCar: Array[1]
}
car.get('isValid')
false
```

However, when I set it correctly, `isValid` doesn't update:

```javascript
car.set('hasWheels', true)
car.errors
Class {
  hasWheels: Array[0]
  isViableCar: Array[0]
}
car.get('isValid')
false
```

Does anyone know why this could be happening? 

ember:             1.11.0
ember-data:        1.0.0-beta.16.1
ember-validations: 2.0.0-alpha.3

**Comment by martndemus** [comment]
I am going to close this issue for now, feel free to reopen this issue if you feel like it's still relevant and we should take a look at it.
