### ISSUE TITLE
Running validations on createRecord

### ISSUE THREAD

**Issue by Jordan4jc** [DockYard/ember-validations#317]
I'm having a little trouble understanding how to run these validations. The example in the readme says they get run when an object is created but I'm using `createRecord` to create a new record and then `.save()` to save it to my firebase store.

When I try to `createRecord` and then run `.validate()` on it I get this in the console

```
Uncaught TypeError: newImage.validate is not a function
```

Which I'm assuming is because `createRecord` does not return an object that the validate method can run on?

I found this issue where someone is trying to make these work in a non `ObjectController` setup which is the same thing I'm trying to do.

https://github.com/dockyard/ember-validations/issues/294

And I followed the gist to set this up but I'm still getting this error when trying to validate.

I'm open to restructuring the way I create these `records` or `objects` and save them to the store if someone can explain why I would do it one way over the other.

**Comment by gideonwhylr** [comment]
@bcardarella any update on this, I'm running into the same issue, and seemingly many are. Let us know - love your work!

**Comment by blaher** [comment]
Same issue here.

**Comment by martndemus** [comment]
I am going to close this issue for now, feel free to reopen this issue if you feel like it's still relevant and we should take a look at it.
