### ISSUE TITLE
build link in documentation is broken

### ISSUE THREAD

**Issue by BenjaminHorn** [DockYard/ember-validations#318]
The documentation says: 

> We will continue to build EmberValidations to the DockYard build server until ember-cli is officially recommended by Ember. You can select a build version from: http://builds.dockyard.com for use in Bower.

but http://builds.dockyard.com seems to be down.

**Comment by derekwsgray** [comment]
It is also down now too, breaking my build.  Using "1.0.0" instead of this URL in bower.json gets no index file...

**Comment by martndemus** [comment]
I am going to close this issue for now, feel free to reopen this issue if you feel like it's still relevant and we should take a look at it.
