### ISSUE TITLE
Deprecation (isServiceFactory) in Ember 1.13

### ISSUE THREAD

**Issue by jeremytm** [DockYard/ember-validations#319]
Ember Inspector (Deprecation Trace): In Ember 2.0 service factories must have an `isServiceFactory` property set to true. You registered (unknown mixin) as a service factory. Either add the `isServiceFactory` property to this factory or extend from Ember.Service.

The deprecation appears during initialisation of the mixin. Here are the trace lines that relate to ember-validations:

```
at lookupValidator (http://localhost:4200/assets/vendor.js:90633:29)
at exports.default.Ember.default.Mixin.create.buildRuleValidator (http://localhost:4200/assets/vendor.js:90744:68)
at exports.default.Ember.default.Mixin.create.buildValidators (http://localhost:4200/assets/vendor.js:90710:16)
at exports.default.Ember.default.Mixin.create.init (http://localhost:4200/assets/vendor.js:90692:12)
```

This is the line in `lookupValidator`:
```javascript
var service = container.lookup('service:validations');
```

**Comment by rwjblue** [comment]
This is fixed on master, by https://github.com/dockyard/ember-validations/pull/307.

**Comment by jcope2013** [comment]
any way to push new npm update with latest deprecation fixes, referencing github master in package.json doesnt seem to work, getting error in my app

**Comment by bcardarella** [comment]
I'll see about pushing an version bump. I've been trying to squeeze in a refactor before I bumped but I haven't had much time to get that done yet.

**Comment by bcardarella** [comment]
done

**Comment by martndemus** [comment]
I am going to close this issue for now, feel free to reopen this issue if you feel like it's still relevant and we should take a look at it.
