### ISSUE TITLE
allowBlank cannot be set to false in format validation

### ISSUE THREAD

**Issue by Fryie** [DockYard/ember-validations#322]
In this line of code: https://github.com/dockyard/ember-validations/blob/master/addon/validators/local/format.js#L21

the format validator just checks whether allowBlank is set to undefined, in which case it disallows blank values. IMO it should also be possible to specify allowBlank: false. At least the current behaviour is very unintuitive.

**Comment by mattmcginnis** [comment]
+1 on this.  If allowBlank is false, it should not allow blank values.

**Comment by martndemus** [comment]
I am going to close this issue for now, feel free to reopen this issue if you feel like it's still relevant and we should take a look at it.
