### ISSUE TITLE
EnumerableUtils is no more in Canary

### ISSUE THREAD

**Issue by rlivsey** [dockyard/ember-validations#323]
`EnumerableUtils` is used in [a](https://github.com/dockyard/ember-validations/blob/15fafa42faf8585df871ff42be4d4d07ddef1d58/test-support/helpers/validate-properties.js#L4) [few](https://github.com/dockyard/ember-validations/blob/15fafa42faf8585df871ff42be4d4d07ddef1d58/addon/mixin.js#L11) [places](https://github.com/dockyard/ember-validations/blob/15fafa42faf8585df871ff42be4d4d07ddef1d58/addon/mixin.js#L144) but has been [removed from Ember](https://github.com/emberjs/ember.js/pull/11455) in Canary in preference to native implementations.

I will try and get a pull request sorted in the morning.

**Comment by bcardarella** [comment]
Yup, with Ember 2.0 we can target >= IE9 which should have `Array.prototype.forEach` and `Array.prototype.filter`

**Comment by rlivsey** [comment]
Should we check for EnumerableUtils existing & fallback to native if not present, or just go the whole hog & use native?

**Comment by bcardarella** [comment]
whole hog, I'm going to target Ember 2.0
