### ISSUE TITLE
Use custom error messages with ember-i18n

### ISSUE THREAD

**Issue by jaimevent** [dockyard/ember-validations#335]
I know that it's possible to translate default error-messages with the ember-i18n-plugin, but I need to translate custom messages.
Actually I've tried this (as described [here](https://github.com/jamesarosen/ember-i18n/wiki/Doc:-Translating-Text#i18nt)):
```javascript
message: Ember.computed('i18n.locale', function() {
          return this.get('i18n').t('form.errors.email');
})
```
and also this
```javascript
message: t('form.errors.email')
```

but none are working, both return an object. Any idea how I could solve this?

Thanks

**Comment by florent-blanvillain** [comment]
Hi, did you find a workaround ?

**Comment by jaimevent** [comment]
Yes, I'm calling a function which sets the messages. It's something like this:
```javascript
init: function() {
	this._super();

  this.send('setLocaleLangTexts');
},
actions: {			
	setLocaleLangTexts: function() {
		this.setProperties({
			'validations.email.presence.message': this.get('i18n').t('form.errors.email'),
		});
	}
}
```

The function `setLocaleLangTexts` is also called every time the locale is changing.

**Comment by florent-blanvillain** [comment]
Great, thank you !
