### ISSUE TITLE
Alpha.3 repository package code contract change

### ISSUE THREAD

**Issue by curtislinden** [DockYard/ember-validations#337]
Hi. First - I LOVE THIS ADDON! Great work Team!!

We noticed that our development checkout of alpha.3 had one contract and then a yesterday checkout of alpha.3 on staging had a seperate contract. Ie: a function went missing!

May I please suggest to use a patch or version bump on any code changes and not republish an existing version!

Best!

**Comment by martndemus** [comment]
I am going to close this issue for now, feel free to reopen this issue if you feel like it's still relevant and we should take a look at it.
