### ISSUE TITLE
Synchronous validation

### ISSUE THREAD

**Issue by olivierlesnicki** [DockYard/ember-validations#341]
Is it possible to have .validate() runs synchronously? The fact that this runs asynchronous means we need to rely more often than not on .observers() and this introduces bad design patterns. The ember community highly recommend using computed properties.

**Comment by bcardarella** [comment]
@olivierlesnicki can you describe your use case?

**Comment by olivierlesnicki** [comment]
This might be a bit hard to explain, and I can't share the code for IP reasons, but here's my use case:
- I have an arbitrary number of properties rendering form inputs on the page
- whenever the user updates an input value, error messages should appear accordingly at the input level
This means I need to create observers for each of these values and trigger .validate() when they are changed. I also store the .isValid value against a property .isPropertyNameValid.

As far as I'm concerned this is OK, the problem rises when I need to know the aggregated validity of the properties and their current values at the same time.

If i set an observer on the properties, I can't guarantee their validity status will have been updated by the time the observer is run.

If i set an observer on the isPropertyNameValid properties, I can't guarantee the validity flag is a reflection of the current value of the property.

**Comment by bcardarella** [comment]
If I am following you, the issue at hand is the the displaying of the error message and when to display them?

**Comment by olivierlesnicki** [comment]
No (sorry this one is a complex one!) the issue is a race condition one:
say I want to make a call to the server as soon as all properties are valid and send all of them across.

Although all properties are marked as valid, it doesn't mean their values are (say the property is changed before the validation has completed). And I end up sending to the server incorrect values.

**Comment by bcardarella** [comment]
It sounds like you want to use the promise returned by the validations:

https://github.com/dockyard/ember-validations/blob/master/tests/unit/validate-test.js#L32-L42

**Comment by olivierlesnicki** [comment]
Tried - and failed. The code gets really complex when adding promises into the mix.
Let me find an actual example and come back to you.

Thanks for your time :)

**Comment by martndemus** [comment]
I am going to close this issue for now, feel free to reopen this issue if you feel like it's still relevant and we should take a look at it.
