### ISSUE TITLE
Please update the README

### ISSUE THREAD

**Issue by krzkrzkrz** [DockYard/ember-validations#343]
`npm install ember-validations --save-dev` installs `2.0.0-alpha.4`. Is the `alpha.4` considered stable? README says 2.0.0. No such version exists...

http://builds.dockyard.com/ points to a dead page.

Furthermore, the README is unclear on how we should get started, which makes this whole process frustratingly hard to work with.

Doing this in a component triggers nothing:

```
import EmberValidations from 'ember-validations';

export default Ember.Component.extend(EmberValidations, {
  validations: {
    'name': {
      presence: true,
      length: { minimum: 5 }
    }
  },
  ...
```

I've tried with the 0.0.0 version and still nothing.

**Comment by laantorchaweb** [comment]
Same issue here, I've used EmberValidations before but now I have this issue with the 0.0.0 version that is being installed with ember install. And if I add the 2.0.0 this error is being throw:

```
npm ERR! notarget Valid install targets:
npm ERR! notarget ["0.0.0","2.0.0-alpha.1","2.0.0-alpha.2","2.0.0-alpha.3","2.0.0-alpha.4"]
```

**Comment by thiagodelgado111** [comment]
Same problem here, the code bellow does nothing... and after I followed the build procedure described on the README, I didn't find were the resulting file was created, the dist folder only contains test files...It's really unclear how to get started. 

```
import EmberValidations from 'ember-validations';

export default Ember.Controller.extend(EmberValidations, {
  validations: {
    'name': {
      presence: true,
      length: { minimum: 5 }
    }
  },
  ...
```

**Comment by philipdesmedt** [comment]
Same problem here. Validations are not running on Ember 1.13.10 and Ember-data 1.13.13

**Comment by thiagodelgado111** [comment]
Guys, could you give us a little help here?  @diogomafra @bcardarella

**Comment by richmolj** [comment]
Not sure if this is the same issue but on Ember 1.13.9 I get "could not find module `ember-validations/index`"

**Comment by BrianSipple** [comment]
+1 

I'm having the same issue as @laantorchaweb

**Comment by brandonparsons** [comment]
I also had a pile of issues trying to use the newer version, and the README instructions not working properly.

FWIW, for the time being I have just dropped `ember-validations 1.0.0` into my `vendor` directory in ember-cli, and will cling to that version for now.

I have a feeling it is going to block me from upgrading to > 2.0 though.

**Comment by maedi** [comment]
beta4 doesn't seem usable (doesn't do anything). Does this addon actually work?

**Comment by fullofcaffeine** [comment]
+1 any news regarding that?

**Comment by kmiyashiro** [comment]
I believe you guys need to change the paths in your validations. For example, if you mix your validations into a controller:

```js
  validations: {
    'name': {
      presence: true,
      length: { minimum: 5 }
    }
  },
```

validates `controller.name`, but you probably want `controller.model.name`.

```js
  validations: {
    'model.name': {
      presence: true,
      length: { minimum: 5 }
    }
  },
```

**Comment by laantorchaweb** [comment]
The problem for me was that the addon is not working, I didn't test a new version to check if the issue persists.

**Comment by bbtb1982** [comment]
+1

**Comment by martndemus** [comment]
I am going to close this issue for now, feel free to reopen this issue if you feel like it's still relevant and we should take a look at it.
