### ISSUE TITLE
Prevent running validation on init?

### ISSUE THREAD

**Issue by balinterdi** [dockyard/ember-validations#353]
When the mixin is initialized, all defined validations are run and set properties on the error object. That means that when the user initially navigates to the form, they will see the errors where an empty value is not allowed (presence: true, format where an empty value does not pass, numericality, etc.).

That might be needed in some cases, although it's rather confusing in most of them. Also, if a certain use case needs it, `object.validate()` can still be run explicitly but as it currently stands, I see no way of not running the validations: https://github.com/dockyard/ember-validations/blob/8809ab4f14a0b1949a9d58674629d51d3ef05cd7/addon/mixin.js#L101

**Comment by bcardarella** [comment]
This is a frequent point of confusion, I created a FAQ for this reason: https://github.com/dockyard/ember-validations/wiki/automatic-validation

Let me know if this makes sense.

**Comment by balinterdi** [comment]
Ok, thank you, this makes sense.
