### ISSUE TITLE
dependentValidationKeys is a misnomer

### ISSUE THREAD

**Issue by pwfisher** [dockyard/ember-validations#355]
The name implies the reverse of the actual relationship (they are dependencies, not dependent) and creates confusion. As you say in the readme,

> `dependentValidationKeys` is the collection of paths relative to this.model that will be observed for changes.

Dependency vs. dependent gives lots of people trouble. I think your readme is quite clear. I suggest the code follow the readme and use the name `observedProperties`.

**Comment by bcardarella** [comment]
@pwfisher the observers are going to changed over to computed properties. The intent is to follow a similar internal API as Ember itself.
