### ISSUE TITLE
Clear validations on submit success

### ISSUE THREAD

**Issue by awwester** [dockyard/ember-validations#357]
I want to clear all the validation styling when submitting a form successfully (remove checkmarks, input borders, etc). I feel like that would be something common but I don't see anything about doing such a thing in the documentation nor browsing through Issues. Is there a way to do this built-in or do I need to go with a different strategy?

**Comment by bcardarella** [comment]
@awwester your actual concern is with the visualization of certain states of the errors. This is a view concern. ember-vaidations concerns itself only with the model layer: https://github.com/dockyard/ember-validations/wiki/automatic-validation

In this case you will likely want some flag to be set based upon the submission state of the form that controls if the error state is shown or not.
