### ISSUE TITLE
Inline Validator throws error: ember_validations.validator is not a function

### ISSUE THREAD

**Issue by benbabics** [DockYard/ember-validations#359]
As outlined in the README, I am importing the EmberValidations and `validator` method:
`import EmberValidations, { validator } from 'ember-validations';`

and using inline for my object property:
`validator(function() { ... })`

I am getting an error thrown:
`TypeError: ember_validations.validator is not a function`

The fix seems to use the EmberValidations that is imported:
`EmberValidations.validator(function() { ... })`

Am I doing something wrong?

**Comment by bcardarella** [comment]
Can you copy/paste the entire validator object?

**Comment by benbabics** [comment]
Sure thing.

```
import Ember from 'ember';
import EmberValidations, { validator } from 'ember-validations';

export default Ember.Mixin.create(EmberValidations.Mixin, {

  validations: {
    date: {
      inline: EmberValidations.validator(function() {
        let date = this.get( 'date' );
        if ( !date ) {
          return 'Date is required.'
        }

        date      = new Date( date );
        let today = new Date( new Date().setHours(0,0,0,0) );

        if ( today >= new Date(date) ) {
          return 'Date must be in the future.'
        }
      })
    }
  }

});
```

**Comment by martndemus** [comment]
I am going to close this issue for now, feel free to reopen this issue if you feel like it's still relevant and we should take a look at it.
