### ISSUE TITLE
validation 'listener'

### ISSUE THREAD

**Issue by shopapps** [DockYard/ember-validations#362]
Hi,

I'm looking for some advise as to the best approach to create a disabled 'Save' button on my form, pending the model validations to be error free.

Currently my validators are defined in the models (not the component).  and the main model has a number of hasMany relationships with other models that are also validated.

I was trying to set an option of:

    saveDisabled: false

which when set true/false does enable disable my button, but I think this would be better done as some kind of computed or observed value e.g.

    saveDisabled: Ember.observer('model','validationCustomer', function() {
    return 'soemthing!!'
    });

what is the best approach to this kind of requirement?

thanks.

**Comment by shopapps** [comment]
Just in case others are struggling with anything similar, after lots of trial an error I have come up with the following option (don't know if its the best method but currently works for me):

    saveDisabled: Ember.computed('model.isValid', 'model.customer.isValid', function(){
        return !(true === (
          this.get('model.isValid') &&
          this.get('model.customer.isValid')
        ));
      }),

**Comment by msmyers** [comment]
I have found that you cannot observe or compute off of a property unless you call ".get(...)" for that property.

Sadly, observers just don't fire. I suspect that the internal code only detects changes for a property inside the .get(..) method.

**Comment by timmyomahony** [comment]
This seems like such a basic use case. I would love some clarification on the best way to go about it

**Comment by martndemus** [comment]
I am going to close this issue for now, feel free to reopen this issue if you feel like it's still relevant and we should take a look at it.
