### ISSUE TITLE
Validations mixin overrides errors field used by ember-data models

### ISSUE THREAD

**Issue by andrei1089** [DockYard/ember-validations#363]
The validations mixin doesn't work fine with ember-data models as it overrides the `errors` field. This is causing failures when backend returns 422 errors and ember-data tries to process them.

**Comment by maartenparmentier** [comment]
same issue here

**Comment by kteague** [comment]
This seems to be an issue with any use of ember-validations with ember-data 2.0.0 or greater? It looks like this could be fixed by renaming the `errors` property used by ember-validations to something like `errors_client`? Is anyone working on getting ember-validations to work with ember 2.0+ yet?

**Comment by maartenparmentier** [comment]
still on 1.13.x here

**Comment by nobesnickr** [comment]
I'm having the same problem, took me about 5 hours to hunt down that was the problem (prob should have checked here first). I'm going to take a stab at jamming through a fix and will update with my progress.

Can something get added to the readme for the time being alerting folks to look out for this? Its pretty much a blocker for production-grade use.

**Comment by nobesnickr** [comment]
I was able to resolve on my side by simply using the DS.Errors object instead of the Ember.A object. Something tells me that is way to simple of a fix so I'll send as a PR and let others check it out and post potential repercussions. We'll definitely need some way of detecting whether or not DS.Errors is available to support backwards compatibility

**Comment by nicolas-dular** [comment]
any updates on this? validations are otherwise pretty useless

**Comment by bcardarella** [comment]
@nicolas-dular this has been addressed in multiple issues. The TL;DR is that you shouldn't mix you validations into ember data and instead use them on the context. (controllers or components)

**Comment by martndemus** [comment]
I am going to close this issue for now, feel free to reopen this issue if you feel like it's still relevant and we should take a look at it.
