### ISSUE TITLE
Controllers Deprecation

### ISSUE THREAD

**Issue by cimtico** [DockYard/ember-validations#364]
How would I go by using this without controllers and just the router model? (considering the model could be a hash and not a full blown Ember.Object).

I'm in the process of incorporating validations to a new app and want to make it work with ember 2+.

**Comment by drewclauson** [comment]
@cimtico This may be helpful for you:

http://emberigniter.com/should-we-use-controllers-ember-2.0/?utm_source=Ember+Weekly&utm_campaign=b10f69dd83-Ember_Weekly_Issue_130&utm_medium=email&utm_term=0_e96229d21d-b10f69dd83-106361197

Bottom line: "For most migrations, renaming export default Ember.Controller.extend(...) to export default Ember.Component.extend(...) will just work, as components partly have the role of controllers."

**Comment by drewclauson** [comment]
@cimtico So, for the time being, I'm using controllers in my Ember 2.1 app.

**Comment by cimtico** [comment]
So this means I'll have to live with the deprecation warning until routable components become available right? (or move the corresponding form into a component).

**Comment by drewclauson** [comment]
What version are you using?  I'm on 2.0.0-alpha.4 and not getting any deprecation warnings and the validations are working for me at this point.

**Comment by cimtico** [comment]
I'm on the latest 1.x version due to some plugins that haven't quite upgraded nicely yet. But plan on upgrading to the latest soon

**Comment by martndemus** [comment]
I am going to close this issue for now, feel free to reopen this issue if you feel like it's still relevant and we should take a look at it.
