### ISSUE TITLE
Cannot import after ember install with Ember 1.13.9

### ISSUE THREAD

**Issue by timiyay** [DockYard/ember-validations#365]
I'm keen to try out `ember-validations`, but attempting to import it crashes my app.

__Steps to reproduce__:  

* versions: Ember 1.13.9, Ember CLI 1.13.8
* install with `ember install ember-validations`
* try to import into a module, as per the docs: `import EmberValidations from 'ember-validations';`

My app will no longer boot, and the JS console says:

```js
Uncaught Error: Could not find module 'ember-validations/index' imported from 'ember-validations'`
```

**Comment by timiyay** [comment]
This same issue has been mentioned [here](https://github.com/dockyard/ember-validations/issues/343#issuecomment-142710481).

**Comment by steven-ferguson** [comment]
Make sure that ```ember install``` installs a valid release. When I did ```ember install ember-validations``` today, it installed version ```"0.0.0"```. Updating my ```package.json``` to a valid release fixed the import issue.

**Comment by martndemus** [comment]
I am going to close this issue for now, feel free to reopen this issue if you feel like it's still relevant and we should take a look at it.
