### ISSUE TITLE
Tried to use i18n, added translations to errors, isn't working

### ISSUE THREAD

**Issue by VincentBons** [DockYard/ember-validations#366]
We tried to use i18n as described in readme.md. Put all the translations in locals/nl/translations.js. 
![screen shot 2015-10-23 at 16 51 08](https://cloud.githubusercontent.com/assets/15103774/10695871/4ae8dcca-79a6-11e5-922f-abcd9347a3a7.png)
It should work automatically now according to the readme.md, but it isn't. Are we doing something wrong? Or is this an issue?

**Comment by Szeliga** [comment]
@VincentBons I've traced the problem to https://github.com/dockyard/ember-validations/blob/master/addon/messages.js#L5

The newest ember-i18n package doesn't work anymore on a global `Ember.I18n` object, but on an injectable service instead - https://github.com/jamesarosen/ember-i18n/wiki/Doc:-i18n-Service

Either revert to ember-i18n 3.x.x (which caused an exception on app start in my project), or we have to come up with a PR for this

**Comment by webPapaya** [comment]
Just also came across this issue and you can easily fix that by just assigning the i18n service to Ember.I18n like that: 

``` javascript 
// Application route
export default Ember.Route.extend({
  i18n: Ember.inject.service(),
  beforeModel() {
    this.set('i18n.locale', 'nl');
    Ember.I18n = this.get('i18n');
  }
});
````
Afterwards your error messages should be displayed as expected.
You should also be able to do the same thing in an initializer.

**Comment by Szeliga** [comment]
Hi @webPapaya and thanks for your input.

I was discussing the approach you proposed with my coworkers and we decided that modifying the global Ember object is a bad idea. 

We are working on a pull request for this, but it is difficult, because there is no container in the part of the lib where messages are defined, so we cannot lookup the service.

**Comment by jbandura** [comment]
It seems the best solution for now is to add the the code that @webPapaya mentioned into instance-initializers (for those using Ember with FastBoot):

```
/* app/instance-initializers/locale.js */
/* global Ember */

export function initialize(application) {
  let i18n = application.container.lookup('service:i18n');
  i18n.set('locale', 'en'); //set your default locale or compute it
  Ember.I18n = i18n;
}

export default {
  name: 'locale',
  initialize: initialize
};
```
We have to hope that guys from ember-validations will fix this soon.

**Comment by gzurbach** [comment]
+1 this solutions works great! It'd be awesome to see a better integration though.

**Comment by VincentBons** [comment]
Great! Thanks for all replies. We've solved it for now by using the i18n key in the message and by using the i18n in the template. This also works well enough.

**Comment by gzurbach** [comment]
Would you mind posting an example?

**Comment by VincentBons** [comment]
Off course:

in controller:
```javascript
validations: {
    firstName: {
       presence: { message: 'errors.blank'}  
    }
}
```
in translations.js
```javascript
export default {
   errors: {
      blank: "Deze waarde mag niet leeg zijn.", // Dutch for 'this value can not be empty'
   }
}
```
in template
```javascript
{{t errors.firstName}}
```

**Comment by gzurbach** [comment]
This is a great idea actually. The only problem I can see with it is if you have params. For instance if a field must contains at least 8 characters the error message would show "Must contain at least 8 characters". Ember-validations' i18n integration would take care of that for you but I'm not sure it would work with that code.

**Comment by VincentBons** [comment]
No, that's right. That isn't working, but we decided just to not use that, its not yet a problem in our app. You could work around this by adding a translation for each param you normally would use, but its not a perfect solution.

**Comment by Kilowhisky** [comment]
Is anyone working on a PR for this still? I willing to give it a shot if no one is ATM.

**Comment by gzurbach** [comment]
I don't think anyone is. I believe ember-validations is not being maintained outside PRs submitted by contributors.

**Comment by jamesarosen** [comment]
A couple of recommendations while we wait for this project to be directly compatible with Ember-I18n v4.x.

You can set `Ember.I18n` in an instance-initializer:
```js
// app/instance-initializers/ember-validations-i18n.js
import Ember from 'ember';
export default {
  name: 'ember-validations-i18n',
  initialize({ registry }) {
    Ember.I18n = registry.lookup('service:i18n');
  }
};
```
Don't forget to tear it down when the app is destroyed lest you leak memory in test runs:
```js
// app/app.js:
const App = Ember.Application.extend({
  modulePrefix: config.modulePrefix,
  podModulePrefix: config.podModulePrefix,
  Resolver,
  destroy() {
    this._super(...arguments);
    if (Ember.I18n != null) {
      Ember.I18n.destroy();
      Ember.I18n = null;
    }
  }
});
```

**Comment by GCorbel** [comment]
Any updates?

It seems it does not work anymore. 

I have this in `app/locales/fr/translations.js`
```
export default {
  errors: {
    blank: "ne peut pas être vide",
  }
};
```

And this in `app/instance`initializers/locale.js` :

```
export function initialize(application) {
  let i18n = application.container.lookup('service:i18n');
  i18n.set('locale', 'fr'); //set your default locale or compute it
  Ember.I18n = i18n;
}

export default {
  name: 'locale',
  initialize: initialize
};
```

And errors are empties. If I remove the translation I can see "Missing translation: errors.blank". I can see than `Ember.I18n.t('errors.empty')` gives `SafeString {string: "ne peut pas être vide"}`. It works when it return a normal string.

@jamesarosen, you may help me on this.

**Comment by GCorbel** [comment]
I think I cannot override [the message mixin](https://github.com/DockYard/ember-validations/blob/master/addon/messages.js) because there is no equivalence in the app folder. I cannot use `reopen` because `import Messages from 'ember-validations/messages';` does not give an EmberObject.

Am I correct. Does someone have a solution?

**Comment by Baukereg** [comment]
Don't use an instance initializer but the beforeHook on the application route instead, just as webPapaya suggested (3th post from top).

**Comment by jonpitch** [comment]
Is there any update on this? With the workarounds mentioned in the thread, I can get `ember-validations` to use my `i18n` strings. However, when I switch locales, the validation strings remain in the previously set language. Any thoughts on how I can swap validation messages if my user changes their locale without reloading the page?

**Comment by martndemus** [comment]
I am going to close this issue for now, feel free to reopen this issue if you feel like it's still relevant and we should take a look at it.
