### ISSUE TITLE
cannot install "ember-validations": "2.0.0" 

### ISSUE THREAD

**Issue by MohamadAtieh** [DockYard/ember-validations#368]
It says version not found when doing `npm install`

**Comment by BenjaminHorn** [comment]
try `"ember-validations": "~ 2.0.0"` or `ember-validations": "2.0.0-alpha.3"`

**Comment by nsharrok** [comment]
I get 
>Error while processing route: details.index Could not find module `ember-validations` imported from `fluvax/controllers/details` 


```
bower ember-validations#~2.0.0-alpha.4          install ember-validations#2.0.0-alpha.4
bower install
├── ember#2.1.0
├── ember-cli-shims#0.0.6
├── ember-cli-test-loader#0.2.1
├── ember-data#2.1.0
├── ember-load-initializers#0.1.7
├── ember-qunit#0.4.11
├── ember-qunit-notifications#0.1.0
├── ember-resolver#0.1.21
├── jquery#1.11.3
├── loader.js#3.3.0
└── qunit#1.19.0
```

fluvax/controllers/details
```
import Ember from 'ember';
import EmberValidations from 'ember-validations';

export default Ember.Controller.extend(EmberValidations,{
 ...
}
```

Seems odd but I get 
```
PS D:\Ember\fluvax> npm list ember-validations
fluvax@0.0.0 D:\Ember\fluvax
└── (empty)

npm ERR! code 1
```

and 

```
PS D:\Ember\fluvax> npm list ember-validations@2.0.0-alpha.4
fluvax@0.0.0 D:\Ember\fluvax
└── ember-validations@2.0.0-alpha.4
```
Is there something wrong with the package files?

Noel

**Comment by ColtonProvias** [comment]
I know this is an old issue, but I thought I should put the solution here for those who are googling it:

Make sure you ember-validations is set to 2.0.0-alpha.4 in package.json.  Then run `rm -rf dist tmp bower_components node_modules` to clear any caches or anything, followed by `npm install` and `bower install`.  The next time you build or serve, it should work then.

**Comment by martndemus** [comment]
I am going to close this issue for now, feel free to reopen this issue if you feel like it's still relevant and we should take a look at it.
