### ISSUE TITLE
How to avoid initial validation?

### ISSUE THREAD

**Issue by glenlivet** [DockYard/ember-validations#372]
When defining a validations in a controller, the validation will be done once after the view is rendered, and the `errors` property will be populated right away. 

Intuitively, I use a `if` helper to show the error message, but with ember-validations all error messages will be displayed even before starting to fill the form, which is very annoying. 

What is the common pattern to handle error message display with ember-validations, so the error message will only display after say blur or manually?

**Comment by bcardarella** [comment]
https://github.com/dockyard/ember-validations/wiki/automatic-validation

**Comment by asermax** [comment]
I've run over the problem of the initial validations materializing every async relationship the model may have validations on, even if it isn't need just yet (eg displaying only some of the model's data).
I think wanting to disable the initial validation is a valid concern, beyond it's recommended or not.

**Comment by wvteijlingen** [comment]
I'm running into the same problem where all relationships with validations are materialised. @asermax: Did you find a way to work around this?

**Comment by martndemus** [comment]
I am going to close this issue for now, feel free to reopen this issue if you feel like it's still relevant and we should take a look at it.
