### ISSUE TITLE
Conditional validation always affects 'isValid'

### ISSUE THREAD

**Issue by shapiroronny** [DockYard/ember-validations#378]
Hey,

I've encountered unexpected behaviors with conditional validators. It seems even if the conditional is false the validation is still taken into consideration when calculating the 'isValid' state of the object.

```javascript
format: {
                "with": /some-regx/,
                allowBlank: false,
                'if' : function(object, validator) {                    
                    return object.get('isSomeValue');
                }
```

When 'isSomeValue' is false the validation does not run, yet 'isValid' is false if the regex does not match.

**Comment by martndemus** [comment]
I am going to close this issue for now, feel free to reopen this issue if you feel like it's still relevant and we should take a look at it.
