### ISSUE TITLE
Ember.String.htmlSafe is ignored inside error messages

### ISSUE THREAD

**Issue by jedld** [DockYard/ember-validations#379]
example: create a validation that uses htmlsafe:

lastName:   { presence: { message: Ember.String.htmlSafe('<a href="http://staging.www.yescredit.com/responsibility">This is a link</a>') } }

Expected:

Error messag should render a link.

Actual:

No link is rendered and string is displayed as is

**Comment by martndemus** [comment]
I am going to close this issue for now, feel free to reopen this issue if you feel like it's still relevant and we should take a look at it.
