### ISSUE TITLE
Clear errors on value change?

### ISSUE THREAD

**Issue by adjohnson916** [DockYard/ember-validations#387]
Should the errors array be cleared on any value change? Right now I'm using the errors array to attach custom error messages, but it's not necessarily cleared when I want because no validation rules change despite that the validated value changes, and I'd like to clear the errors array.

If this isn't right, do you have any suggestions how I could achieve this, besides managing my own server-side error array, and besides relying on custom observers that might get bound in the wrong order (clearing errors newly attached by ember-validations after a value change)?

**Comment by IntellectProductions** [comment]
I'm having the same issue... my form acts like there is errors all the time so I'm probably switching to jquery validation plugin.

**Comment by martndemus** [comment]
I am going to close this issue for now, feel free to reopen this issue if you feel like it's still relevant and we should take a look at it.
