### ISSUE TITLE
Not able to do `npm install`

### ISSUE THREAD

**Issue by GCorbel** [DockYard/ember-validations#391]
Hi try to do a npm install and I always have this error : 

    npm ERR! Linux 3.13.0-24-generic
    npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
    npm ERR! node v5.4.0
    npm ERR! npm  v3.3.12
    npm ERR! path /app/node_modules/ember-cli/node_modules/broccoli/node_modules/connect/node_modules/debug/node_modules/ms
    npm ERR! code ENOENT
    npm ERR! errno -2
    npm ERR! syscall rename

    npm ERR! enoent ENOENT: no such file or directory, rename '/app/node_modules/ember-cli/node_modules/broccoli/node_modules/connect/node_modules/debug/node_modules/ms' -> '/app/node_modules/ember-cli/node_modules/ms'
    npm ERR! enoent This is most likely not a problem with npm itself
    npm ERR! enoent and is related to npm not being able to find a file.
    npm ERR! enoent

    npm ERR! Please include the following file with any support request:
    npm ERR!     /app/npm-debug.log

It's not a problem of cache, I cleared it. The problem comes from ember-cli. I think it's an old version. Can someone try to install dependencies form scratch and confirm the problem?

**Comment by martndemus** [comment]
I am going to close this issue for now, feel free to reopen this issue if you feel like it's still relevant and we should take a look at it.
