### ISSUE TITLE
Property set failed: object in path "errors.model.course" could not be found or was destroyed.

### ISSUE THREAD

**Issue by GCorbel** [DockYard/ember-validations#392]
I have this validation : 

    validations: {
      'model.course.id': {
        presence: true
      }
    }

And it produce : 

    Property set failed: object in path "errors.model.course" could not be found or was destroyed.

I solve the problem by changing [this line](https://github.com/dockyard/ember-validations/blob/master/addon/mixin.js#L101) with `Property set failed: object in path "errors.model.course" could not be found or was destroyed.`.

I cannot contribute because of #391

**Comment by lukeclewlow** [comment]
Hi I am also having this problem, but do not follow exactly what your solution is?

**Comment by GCorbel** [comment]
You can use a custom validator and check if there is a course. No better solution for now.

**Comment by HenryVonfire** [comment]
Actually, you can create an `alias` of `model.course` and it should work. 

```
course:Ember.computed.alias('model.course'),
validations: {
  'course.id': {
    presence: true
  }
```
}

**Comment by zeldal** [comment]
@HenryVonfire  it's better to fix, rather then writing 

> Ember.computed.alias('model.course')

for the whole model based validations. Is there any plan to fix, if not we can push change asap. 
Expecting contributors to apply and release.

**Comment by HenryVonfire** [comment]
@zeldal yes, but the project has been in `alpha.4` for half a year if I'm not mistaken so I don't know when a fix will be released. In any case it's just a suggestion.

**Comment by martndemus** [comment]
I am going to close this issue for now, feel free to reopen this issue if you feel like it's still relevant and we should take a look at it.
