### ISSUE TITLE
revalidate x property while validating y property using inline validation

### ISSUE THREAD

**Issue by onmission** [DockYard/ember-validations#396]
Hi, 
I have a scenario where one input field's value can trigger validation message to appear in two different fields. That works. but When user corrects any of those two invalid fields I want remove validation message from both of them. i.e. I need to be able to call .validate() on a different property or whole model, from an inline validation function. Doesn't that work?

If below code makes sense: where if name or address changes i want to be able to validate both, 

```
addressChangeMsg: function() {
  if(//something)
 {
  this.set('displayError',true);
  return 'provide address or name';
 }
else
{
 //validate the whole model so name inline validate triggers and it clears the error from itself
}
}.property('zip','name','address'),

nameChangeMsg: function() {
  if(//something)
 {
  this.set('displayError',true); 
  return 'provide address or name';
 }
else
{
 //validate the whole model so address inline validate triggers and it clears the error from itself
}

}.property('zip','name','address')


validations: {
address: {
allowBlank: true
},
inline: validator(function() {
        return this.get('addressChangeMsg');
      })
},
name: {
allowBlank: true
},
inline: validator(function() {
        return this.get('nameChangeMsg');
      })
}
}
```

**Comment by courajs** [comment]
Could you fix your code formatting? It's difficult to read as is

**Comment by martndemus** [comment]
I am going to close this issue for now, feel free to reopen this issue if you feel like it's still relevant and we should take a look at it.
