### ISSUE TITLE
Question about Ember-CLI acceptance

### ISSUE THREAD

**Issue by haldiggs** [DockYard/ember-validations#398]
I swear I am still new to Ember simply because everytime I start a new app I have to re-learn Ember. :-)

happily though.

I have a question about the statement from this site "We will continue to build EmberValidations to the DockYard build server until ember-cli is officially recommended by Ember."

I thought Ember-CLI was almost the only way to use it... at least if you want to use any plugins it seems so. Are there reasons I should not use this package?

**Comment by floqqi** [comment]
Any comment on this @bcardarella (or anyone else)? Since ember-cli is "the way to go" since at least Ember 2.

**Comment by martndemus** [comment]
I am going to close this issue for now, feel free to reopen this issue if you feel like it's still relevant and we should take a look at it.
