### ISSUE TITLE
Can I pass a computed value to a validator?

### ISSUE THREAD

**Issue by ironyinabox** [DockYard/ember-validations#400]
I'd like to be able to do something like this;

    validations: {
        'content.name': {
            presence: true,
            exclusion: { in: listOfComputedNames , message: 'already exists'}
        }
   }

But how do I get a function, or array computed elsewhere in there?

**Comment by codeNgJon** [comment]
I'm interested to know the outcome of this question @ironyinabox since I am trying to do the same.

**Comment by ironyinabox** [comment]
The answer is no; I ended up writing my own validation system from scratch, based loosely on this one, as well as a few others I read about. I didn't take very long, and has more features than this package now.

**Comment by bcardarella** [comment]
@ironyinabox unfortunately this library did not get into CP validations. It was a goal but we didn't meet in. This library has also been deprecated in favor of `ember-changeset-validations`: https://github.com/DockYard/ember-validations#warning
