### ISSUE TITLE
Validating dynamic form

### ISSUE THREAD

**Issue by sibijohn72** [DockYard/ember-validations#401]
Hi, 
I am trying to write validations for a dynamic form. While validating the regex on a text field it throws this error "this.options.with.test is not a function" in format.js. The regex that i am trying to validate is /^\d+$/. The following is my code snippet.
```
`if (wizardStepFields.regExVal !== null) {
                  validationsItem.format = {};
                  validationsItem.format.with = wizardStepFields.regExVal;
                  validationsItem.format.message = "invalid value";

               }`

```

Here wizardStepFields.regExVal has the value "/^\d+$/"

**Comment by martndemus** [comment]
I am going to close this issue for now, feel free to reopen this issue if you feel like it's still relevant and we should take a look at it.
