### ISSUE TITLE
Custom Validator documantation is not clear

### ISSUE THREAD

**Issue by ykaragol** [DockYard/ember-validations#402]
[Custom validator documentation](https://github.com/DockYard/ember-validations#custom-validators) is not clear and have following issues:

- What's meaning of the header "With Ember-CLI"? Is there any blueprint that can called by ember-cli?
- Do user need to initialize a factory or lookup to find the custom validators placed on _"my-app/app/validators/<name>"_ ?
- What about pod structure?
- What is the meaning of "global object" mentioned at _"You can add your validators to the global object"_ ?

**Comment by martndemus** [comment]
I am going to close this issue for now, feel free to reopen this issue if you feel like it's still relevant and we should take a look at it.
