### ISSUE TITLE
Cannot read property 'invoke' of undefined.

### ISSUE THREAD

**Issue by mnowik** [DockYard/ember-validations#405]
I am running a validation inside a component. The first time I trigger the validation, it is working perfectly. Once the form is valid, I transition to a new route. Then, if a go back to the previous page and trigger `this.validate()` again, I get this error message:
`Uncaught TypeError: Cannot read property 'invoke' of undefined` ([code](https://github.com/DockYard/ember-validations/blob/2e949d3ee77f2b6c614cbf0a5d7bd9e9d1d239be/addon/mixin.js#L165))

It seems to be linked to this issue #123, however I am already using the `.on('init')` handler.

ember-cli: 1.13.1
ember-validations: ~2.0.0-alpha.4

**Comment by martndemus** [comment]
I am going to close this issue for now, feel free to reopen this issue if you feel like it's still relevant and we should take a look at it.
