### ISSUE TITLE
Confirmation validator should accept custom "propertyConfirmation" name

### ISSUE THREAD

**Issue by mciastek** [DockYard/ember-validations#409]
Hi,

I'm using confirmation validator for validating password match, but that validator check value named according to `propertyName + 'Confirmation'` pattern. I think it would be nice to be able to defined what property should validator check, e.g.:

```js
validations: {
  'model.password': {
      confirmation: {
        propertyName: 'password_confirmation'
      }
    }
}
```

What do you think?

Regards

**Comment by martndemus** [comment]
I am going to close this issue for now, feel free to reopen this issue if you feel like it's still relevant and we should take a look at it.
