### ISSUE TITLE
update needed? DEPRECATION: Using the injected `container` is deprecated

### ISSUE THREAD

**Issue by haldiggs** [DockYard/ember-validations#411]
DEPRECATION: Using the injected `container` is deprecated. Please use the `getOwner`

Is this project going to be updated in the future?

using Ember 2.4.0

**Comment by bcardarella** [comment]
Can you put together a PR for this?

We're going to release a 2.0 without any additional feature development. It should be used for bug/deprecation fixes only. I've begun work on 3.0 which will be drastically different (in a good way, I hope)

**Comment by haldiggs** [comment]
I really wish I could, but I'm not as confident in my Ember skills as I should be, plus I'm in the last phases of a project in the office. I'll look forward to testing anything that comes up (2.x). Thanks for commenting quickly.

**Comment by huberts** [comment]
I can see that this deprecation has been already managed in the project. Could you close the issue? And - if I may ask - release a new version (even alpha)?

**Comment by jozefvaclavik** [comment]
This is fixed in master. Seems like this commit solved the issue https://github.com/DockYard/ember-validations/commit/b86fa61fb316befb77c4c5c0a6f394aec955dbfe

**Comment by Baukereg** [comment]
+1 for a new version tag. Until then you can refer to the latest commit:

```
"ember-validations": "git@github.com:DockYard/ember-validations.git#5502c4c"
```

**Comment by alejandrodevs** [comment]
+1 for a new version tag.

**Comment by myrkox** [comment]
+1 for new version

**Comment by TeodorSolvic** [comment]
+1 for new version

**Comment by eruizdechavez** [comment]
Please use the reaction button at the issue instead. Use the comments if you are going to contribute with something useful on the thread.

**Comment by martndemus** [comment]
I believe we fixed this.
