### ISSUE TITLE
Validations not working when using models

### ISSUE THREAD

**Issue by rishimukherjee** [DockYard/ember-validations#414]
I have
 `validations: {
    	'store.businessName': {
      		presence: true,
      		presence: {
      			message: "Cannot be blank"
      		},
      		length: { 
      			minimum: 2, 
      			messages: { 
      				tooShort: 'Should be at least 2 characters'
      			} 
      		}
    	},
}`

I have this in a component. The validations are not working when I am using 'store.businessName'. If I am using 'businessName', it works. But that way I am not able to use models in my app. 

That said, I can access, `this.get('store.businessName')` in a function outside validations. 

What can be the issue?

**Comment by martndemus** [comment]
I am going to close this issue for now, feel free to reopen this issue if you feel like it's still relevant and we should take a look at it.
