### ISSUE TITLE
npm install ember-validations@2.0.0-alpha.4 doesn't get latest commit

### ISSUE THREAD

**Issue by djbreen7** [DockYard/ember-validations#416]
Ironically, I've run into the deprecation issue for using `Object.keys` instead of `Ember.keys` in numericality, line 43. I've tried 

  `rm -rf tmp dist node_modules bower_components`
  ` npm prune`
  `npm cache clean`
  `bower prune`
  `bower cache clean`
  `bower install`
  `npm install` & also removing it from devDependencies and running `npm install --save-dev ember-validations` or `npm install --save-dev ember-validations@2.0.0-apha.4`

With all this trouble, I still don't get the most up-to-date version. Does a new release just need to be made, or am I missing something?

For the record: changing package.json to have `"ember-validations": "git+https://github.com/DockYard/ember-validations.git"` instead does work.

**Comment by estshy** [comment]
@djbreen7 You should avoid fetching always the newest commit as your code might break in future. You can keep reference to particular commit by doing
`git://github.com/DockYard/ember-validations.git#5502c4c5ba538d9a64b7c2960884ad676b6396c4`

Anyway I completely agree that new release should be made.

**Comment by martndemus** [comment]
I am going to close this issue for now, feel free to reopen this issue if you feel like it's still relevant and we should take a look at it.
