### ISSUE TITLE
pushObject / addObject is not a function

### ISSUE THREAD

**Issue by sibijohn72** [DockYard/ember-validations#420]
I recently moved from ember 1.x to 2.6. I am not able to use addObject/ pushObject like i used to.

`import Ember from 'ember';

export default Ember.Controller.extend({
	test:['sibi','john'],
	init:function() {
		this.get('test').pushObject('sebastian');
	}
});`

This throws an error like pushObject is not a function. What is the workaround? Thank you.

**Comment by bcardarella** [comment]
We recommend migrating away from ember-validations and towards ember-changeset-validations: https://github.com/dockyard/ember-changeset-validations
