### ISSUE TITLE
Why did you unpublish versions compatible with 1.0?

### ISSUE THREAD

**Issue by konradjurk** [DockYard/ember-validations#434]

**Comment by bcardarella** [comment]
Can you explain what you're asking? Nothing was ever unpublished.

**Comment by konradjurk** [comment]
I changed nothing in my build and I get this npm error:

```
[Step 1/7] npm ERR! No compatible version found: ember-validations@^1.0.1

[17:07:15][Step 1/7] npm ERR! Valid install targets:

[17:07:15][Step 1/7] npm ERR! 2.0.0-alpha.5, 2.0.0-alpha.4, 2.0.0-alpha.3, 2.0.0-alpha.2, 2.0.0-alpha.1, 0.0.0
```

**Comment by bcardarella** [comment]
This is really odd:

```shell
➜  ~ npm show ember-validations@* version
0.0.0
```

I haven't made any changes to npm. Let me contact them to see what is going on

**Comment by konradjurk** [comment]
Thanks :)

**Comment by bcardarella** [comment]
Actually, these appear to be the installed versions:

```shell
➜  ~ npm show ember-validations versions

[ '0.0.0',
  '2.0.0-alpha.1',
  '2.0.0-alpha.2',
  '2.0.0-alpha.3',
  '2.0.0-alpha.4',
  '2.0.0-alpha.5' ]
```

I believe the version you are attempting to install was never published to npm. Are you able to use any of the 2.x alpha versions?

**Comment by konradjurk** [comment]
Thanks for your help :)

Seems like 1.0.1 really has never been published to npm. I think my previous builds didn't fail because they worked on a cached node_modules directory and my build today didn't. I am going back to this commit 5502c4c5ba538d9a64b7c2960884ad676b6396c4.
