### ISSUE TITLE
Getting "TypeError: this.parentController.childControllers is undefined" when setting itemController on each helper

### ISSUE THREAD

**Issue by dshrestha** [DockYard/ember-validations#65]
In my app I needed to set itemController for #each helper and when I did that ember-validations cause js issue. To give some more context to the problem: http://stackoverflow.com/questions/20529723/controller-support-for-nested-model-data

Here is a jsbin link to demonstrate the issue: 
http://jsbin.com/UROCObi/5/

I couldn't find cdnjs link to ember-validations so have pasted in whole lib there. Please have a look, you probably have better grasp of this issue and the reason behind it.

Thanks,
Dee

**Comment by martndemus** [comment]
I am going to close this issue for now, feel free to reopen this issue if you feel like it's still relevant and we should take a look at it.
